In [2]:
import pandas as pd
import numpy as np

In [3]:
gdp_raw = pd.read_csv("../data/raw/SAGDP/SAGDP2__ALL_AREAS_1997_2024.csv")

In [4]:
gdp = gdp_raw.copy()

In [5]:
gdp.head()

,GeoFIPS,GeoName,Region,TableName,LineCode,IndustryClassification,Description,Unit,1997,1998,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,"""00000""",United States *,,SAGDP2,1.0,...,All industry total,Millions of current dollars,8577552.0,9062817.0,...,18295019.0,18804913.0,19612102.0,20656516.0,21539982.0,21375281.0,23725645.0,26054614.0,27811517.0,29298013.0
1,"""00000""",United States *,,SAGDP2,2.0,...,Private industries,Millions of current dollars,7431989.0,7871498.0,...,15951002.0,16413054.0,17156255.0,18097765.0,18909779.0,18663991.0,20917717.0,23128892.0,24712793.0,26001672.0
2,"""00000""",United States *,,SAGDP2,3.0,11,"Agriculture, forestry, fishing and hunting",Millions of current dollars,108635.0,100746.0,...,182147.0,167492.0,176840.0,177117.0,164214.0,164383.0,230723.0,294048.0,270441.0,269686.0
3,"""00000""",United States *,,SAGDP2,4.0,111-112,Farms,Millions of current dollars,88135.0,80020.0,...,146259.0,130270.0,138733.0,136825.0,122630.0,120506.0,185707.0,247070.0,218198.0,215830.0
4,"""00000""",United States *,,SAGDP2,5.0,113-115,"Forestry, fishing, and related activities",Millions of current dollars,20501.0,20726.0,...,35887.0,37222.0,38107.0,40291.0,41585.0,43877.0,45016.0,46978.0,52243.0,53856.0

In [6]:
gdp[gdp["Description"] == "All industry total "]

,GeoFIPS,GeoName,Region,TableName,LineCode,IndustryClassification,Description,Unit,1997,1998,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,"""00000""",United States *,,SAGDP2,1.0,...,All industry total,Millions of current dollars,8577552.0,9062817.0,...,18295019.0,18804913.0,19612102.0,20656516.0,21539982.0,21375281.0,23725645.0,26054614.0,27811517.0,29298013.0
96,"""01000""",Alabama,5,SAGDP2,1.0,...,All industry total,Millions of current dollars,105381.4,110838.8,...,203113.3,208824.3,216615.5,226263.8,234798.2,235859.0,260325.0,286873.3,309543.8,325345.1
188,"""02000""",Alaska,8,SAGDP2,1.0,...,All industry total,Millions of current dollars,25859.1,24387.8,...,51574.2,51121.8,53550.9,54762.0,54549.6,51861.7,59363.0,65682.5,68232.7,71567.2
280,"""04000""",Arizona,6,SAGDP2,1.0,...,All industry total,Millions of current dollars,132694.8,144393.2,...,298942.2,313787.1,333099.0,353671.0,375376.7,390503.2,438136.0,488722.2,530105.0,570088.6
372,"""05000""",Arkansas,5,SAGDP2,1.0,...,All industry total,Millions of current dollars,59925.0,62852.0,...,118573.6,120987.4,123882.6,129213.8,132625.8,136145.9,154261.8,167863.5,178114.8,188339.6
464,"""06000""",California,8,SAGDP2,1.0,...,All industry total,Millions of current dollars,1068048.6,1143672.5,...,2487156.4,2586485.2,2740550.3,2899530.9,3068629.7,3072927.6,3418256.1,3618289.7,3827007.3,4048108.1
556,"""08000""",Colorado,7,SAGDP2,1.0,...,All industry total,Millions of current dollars,136624.4,149653.7,...,320895.9,330565.9,350209.1,373923.1,397843.6,396981.1,445781.3,499197.4,533268.6,557633.0
648,"""09000""",Connecticut,1,SAGDP2,1.0,...,All industry total,Millions of current dollars,138467.0,145299.2,...,260648.5,264760.4,273875.1,280535.4,286451.9,278747.9,297366.0,321625.2,341851.8,356834.9
740,"""10000""",Delaware,2,SAGDP2,1.0,...,All industry total,Millions of current dollars,33302.2,37170.6,...,72352.5,70021.5,69555.6,73376.0,78710.5,77757.2,83554.7,97030.4,103332.5,110971.8
832,"""11000""",District of Columbia,2,SAGDP2,1.0,...,All industry total,Millions of current dollars,52581.6,54877.4,...,124753.6,129933.5,134298.8,141240.2,145071.4,146854.6,156581.3,165106.2,174250.7,184297.7
924,"""12000""",Florida,5,SAGDP2,1.0,...,All industry total,Millions of current dollars,401744.2,428595.6,...,918464.3,964500.8,1014866.9,1072085.6,1133718.0,1144653.2,1300807.8,1473688.1,1624642.3,1726709.9
1016,"""13000""",Georgia,5,SAGDP2,1.0,...,All industry total,Millions of current dollars,242371.9,265146.4,...,525516.8,554903.2,583543.3,612803.4,646695.8,638488.3,706004.6,785922.7,835755.3,881508.2
1108,"""15000""",Hawaii,8,SAGDP2,1.0,...,All industry total,Millions of current dollars,37701.7,37503.0,...,81410.2,84287.2,87436.4,90933.5,93240.2,84788.0,93684.2,103954.5,111740.2,117627.4
1200,"""16000""",Idaho,7,SAGDP2,1.0,...,All industry total,Millions of current dollars,29699.5,31352.7,...,66064.9,69185.2,72935.1,79072.4,84429.4,88056.8,99884.1,112609.7,120588.1,129018.2
1292,"""17000""",Illinois,3,SAGDP2,1.0,...,All industry total,Millions of current dollars,416015.1,436533.4,...,802592.0,813561.6,832826.8,871024.2,895601.8,860807.8,947223.9,1037735.9,1100794.1,1148106.1
1384,"""18000""",Indiana,3,SAGDP2,1.0,...,All industry total,Millions of current dollars,170924.6,185336.3,...,333163.8,342716.6,357535.8,377376.9,384838.7,378293.0,425270.9,467679.6,496849.5,519516.5
1476,"""19000""",Iowa,4,SAGDP2,1.0,...,All industry total,Millions of current dollars,82808.8,84629.7,...,181471.7,183834.8,187125.0,193155.1,196262.5,199449.6,225055.3,244156.8,253166.5,265794.5
1568,"""20000""",Kansas,4,SAGDP2,1.0,...,All industry total,Millions of current dollars,74643.2,78242.3,...,155699.0,162144.5,166273.6,173373.0,176068.8,175385.6,188993.3,213368.8,224851.3,230522.1
1660,"""21000""",Kentucky,5,SAGDP2,1.0,...,All industry total,Millions of current dollars,104878.1,110020.1,...,194621.2,197944.8,203564.0,210509.1,220678.8,218948.6,238693.7,262586.6,283267.7,295375.3
1752,"""22000""",Louisiana,5,SAGDP2,1.0,...,All industry total,Millions of current dollars,116423.1,120228.8,...,234324.2,227440.3,239830.7,256444.4,257499.0,233652.0,273063.3,304299.3,318044.3,329172.8
1844,"""23000""",Maine,1,SAGDP2,1.0,...,All industry total,Millions of current dollars,30574.2,32412.8,...,58755.8,61092.2,63000.6,66216.0,69708.7,72309.7,79407.6,86310.6,93743.8,99174.1
1936,"""24000""",Maryland,2,SAGDP2,1.0,...,All industry total,Millions of current dollars,159167.8,169360.1,...,367314.1,386496.4,399714.5,410771.8,419391.6,413804.5,447714.3,481861.4,515035.9,546028.4
2028,"""25000""",Massachusetts,1,SAGDP2,1.0,...,All industry total,Millions of current dollars,236435.6,247686.8,...,497767.0,514108.0,530129.4,559605.0,588069.5,592855.5,650308.8,696323.1,737867.4,778523.4
2120,"""26000""",Michigan,3,SAGDP2,1.0,...,All industry total,Millions of current dollars,299832.7,311088.2,...,479222.7,494752.5,505101.5,525240.8,540237.3,530161.3,573329.4,624173.2,676030.8,702466.9
2212,"""27000""",Minnesota,4,SAGDP2,1.0,...,All industry total,Millions of current dollars,157345.9,167867.4,...,336762.0,345248.8,354721.9,372439.2,384850.2,378969.4,416141.9,457393.8,483222.0,507687.8
2304,"""28000""",Mississippi,5,SAGDP2,1.0,...,All industry total,Millions of current dollars,58517.2,61332.3,...,106623.9,107795.4,110281.4,113166.4,116135.7,117441.6,130404.6,141724.2,151511.9,158192.4
2396,"""29000""",Missouri,4,SAGDP2,1.0,...,All industry total,Millions of current dollars,163101.1,170122.2,...,299597.7,304143.3,311273.8,320451.6,334750.2,335970.8,366193.1,397536.9,428887.3,448713.7
2488,"""30000""",Montana,7,SAGDP2,1.0,...,All industry total,Millions of current dollars,19301.7,20414.4,...,46542.4,45859.4,48470.5,51152.1,52715.6,53057.3,60314.8,69087.8,74690.3,78441.0
2580,"""31000""",Nebraska,4,SAGDP2,1.0,...,All industry total,Millions of current dollars,49880.0,51849.9,...,117402.3,119389.8,123219.9,127954.4,132848.2,135014.5,150952.5,167840.2,183780.9,189242.7
2672,"""32000""",Nevada,8,SAGDP2,1.0,...,All industry total,Millions of current dollars,60255.0,65332.2,...,145786.8,153318.0,163199.1,172547.9,184611.1,176178.7,202091.8,232437.9,253443.3,269010.5
2764,"""33000""",New Hampshire,1,SAGDP2,1.0,...,All industry total,Millions of current dollars,38122.5,40747.7,...,77385.8,79759.7,81179.6,83859.4,87868.2,89041.6,99433.3,106824.6,114427.8,119336.6
2856,"""34000""",New Jersey,2,SAGDP2,1.0,...,All industry total,Millions of current dollars,307140.9,318104.0,...,565807.7,578651.4,590086.7,619340.2,643317.7,632562.3,693733.8,756465.6,806894.0,846000.4
2948,"""35000""",New Mexico,6,SAGDP2,1.0,...,All industry total,Millions of current dollars,52575.6,50573.1,...,90779.4,90476.0,93210.1,98838.2,103821.0,101035.5,113781.7,129469.1,138526.0,147084.9
3040,"""36000""",New York,2,SAGDP2,1.0,...,All industry total,Millions of current dollars,716104.7,744958.9,...,1498474.7,1556830.0,1624800.7,1710665.6,1787470.9,1782502.4,1934524.0,2071075.2,2182549.0,2322138.9
3132,"""37000""",North Carolina,5,SAGDP2,1.0,...,All industry total,Millions of current dollars,234571.9,246721.8,...,508672.4,528284.3,546810.1,568037.3,592449.6,600226.9,660804.7,729761.9,794838.0,844209.0
3224,"""38000""",North Dakota,4,SAGDP2,1.0,...,All industry total,Millions of current dollars,15796.6,16842.7,...,56952.2,52666.3,56530.2,60377.1,60892.5,56321.4,64830.0,75052.1,77898.1,80058.3
3316,"""39000""",Ohio,3,SAGDP2,1.0,...,All industry total,Millions of current dollars,343513.7,361479.3,...,615275.5,627294.7,652187.5,672540.1,702914.8,692938.3,764161.4,830498.8,883957.1,923140.6
3408,"""40000""",Oklahoma,6,SAGDP2,1.0,...,All industry total,Millions of current dollars,79293.7,81778.6,...,187364.7,182238.8,192538.6,204193.9,205992.7,192222.0,219132.4,247541.5,255933.2,263695.1
3500,"""41000""",Oregon,8,SAGDP2,1.0,...,All industry total,Millions of current dollars,101418.2,105016.4,...,200592.6,211782.4,225534.5,238466.9,248781.8,250660.6,276367.7,297084.3,314895.0,330250.1
3592,"""42000""",Pennsylvania,2,SAGDP2,1.0,...,All industry total,Millions of current dollars,357525.6,373515.0,...,716534.3,733165.9,754318.0,780620.7,802233.1,778297.2,844875.5,916861.7,966444.0,1007873.9
3684,"""44000""",Rhode Island,1,SAGDP2,1.0,...,All industry total,Millions of current dollars,28963.2,30835.3,...,56604.0,57714.6,58771.6,60064.9,62814.7,61980.9,67060.0,71978.2,76313.5,80381.1
3776,"""45000""",South Carolina,5,SAGDP2,1.0,...,All industry total,Millions of current dollars,97453.8,103688.6,...,207510.0,217555.5,224937.6,236561.7,249575.7,248952.7,272464.9,305070.0,332946.8,357074.4
3868,"""46000""",South Dakota,4,SAGDP2,1.0,...,All industry total,Millions of current dollars,19062.3,20257.8,...,48678.9,49842.6,51615.1,53349.5,55175.8,56847.3,63337.7,69425.6,74458.8,76795.8
3960,"""47000""",Tennessee,5,SAGDP2,1.0,...,All industry total,Millions of current dollars,154861.9,167783.0,...,326382.5,339350.2,355417.5,369713.2,385833.0,391588.6,443419.7,490587.0,531246.8,561201.2
4052,"""48000""",Texas,6,SAGDP2,1.0,...,All industry total,Millions of current dollars,610659.8,648243.1,...,1585985.9,1582981.5,1667313.0,1808026.9,1864872.3,1810670.2,2117013.7,2476903.2,2637237.6,2769766.2
4144,"""49000""",Utah,7,SAGDP2,1.0,...,All industry total,Millions of current dollars,57812.0,62070.1,...,149762.1,159330.6,172075.0,186805.7,201312.2,206240.5,233320.9,261548.5,283230.8,299471.3
4236,"""50000""",Vermont,1,SAGDP2,1.0,...,All industry total,Millions of current dollars,15443.4,16197.7,...,31152.4,31840.2,32589.2,33482.6,34760.3,34572.3,37290.8,41211.2,43931.6,46276.1
4328,"""51000""",Virginia,5,SAGDP2,1.0,...,All industry total,Millions of current dollars,215419.2,232569.9,...,485540.9,499032.4,515167.2,537158.3,561701.8,566101.5,616187.9,665624.7,722767.4,761733.8
4420,"""53000""",Washington,8,SAGDP2,1.0,...,All industry total,Millions of current dollars,193769.5,209222.5,...,467590.6,489790.2,527169.4,570337.8,608643.4,617739.1,683367.0,741002.8,801455.5,856013.6
4512,"""54000""",West Virginia,5,SAGDP2,1.0,...,All industry total,Millions of current dollars,38781.2,40258.9,...,71713.4,71248.9,75172.4,79794.3,80242.4,77536.5,87178.8,98824.1,101479.9,106475.1
4604,"""55000""",Wisconsin,3,SAGDP2,1.0,...,All industry total,Millions of current dollars,153536.2,163021.5,...,308304.5,315420.0,321886.8,335144.3,346906.6,344691.0,368997.3,403570.3,431913.9,453298.6
4696,"""56000""",Wyoming,7,SAGDP2,1.0,...,All industry total,Millions of current dollars,14673.0,14833.2,...,38624.8,36105.9,37620.3,39614.5,40029.5,36982.7,42410.6,49570.4,51350.1,51498.1
4788,"""91000""",New England,1,SAGDP2,1.0,...,All industry total,Millions of current dollars,488005.9,513179.3,...,982313.4,1009275.1,1039545.4,1083763.3,1129673.3,1129507.8,1230866.5,1324272.9,1408135.9,1480526.3
4880,"""92000""",Mideast,2,SAGDP2,1.0,...,All industry total,Millions of current dollars,1625822.8,1697986.0,...,3345236.8,3455098.6,3572774.4,3736014.5,3876195.2,3831778.2,4160983.6,4488400.5,4748506.1,5017311.1
4972,"""93000""",Great Lakes,3,SAGDP2,1.0,...,All industry total,Millions of current dollars,1383822.3,1457458.8,...,2538558.4,2593745.5,2669538.3,2781326.3,2870499.2,2806891.4,3078983.0,3363657.8,3589545.5,3746528.7
5064,"""94000""",Plains,4,SAGDP2,1.0,...,All industry total,Millions of current dollars,562637.8,589812.1,...,1196563.7,1217270.1,1250759.3,1301100.0,1340848.0,1337958.6,1475503.8,1624774.2,1726264.9,1798814.8
5156,"""95000""",Southeast,5,SAGDP2,1.0,...,All industry total,Millions of current dollars,1830328.7,1950036.3,...,3901056.5,4037867.5,4210089.2,4411751.3,4611953.7,4609594.9,5143616.9,5712825.3,6184158.9,6535336.9
5248,"""96000""",Southwest,6,SAGDP2,1.0,...,All industry total,Millions of current dollars,875223.8,924988.0,...,2163072.2,2169483.3,2286160.7,2464730.0,2550062.7,2494430.9,2888063.9,3342636.0,3561801.9,3750634.8
5340,"""97000""",Rocky Mountain,7,SAGDP2,1.0,...,All industry total,Millions of current dollars,258110.6,278324.1,...,621890.0,641047.0,681310.1,730567.7,776330.2,781318.5,881711.7,992013.8,1063127.8,1116061.6
5432,"""98000""",Far West,8,SAGDP2,1.0,...,All industry total,Millions of current dollars,1487052.1,1585134.4,...,3434110.9,3576784.8,3797440.5,4026579.0,4258455.7,4254155.7,4733129.8,5058451.6,5376774.0,5692577.0

In [7]:
gdp["Description"] = gdp["Description"].str.strip()

In [8]:
gdp = gdp[gdp["Description"] == "All industry total"]

In [9]:
gdp.head()

,GeoFIPS,GeoName,Region,TableName,LineCode,IndustryClassification,Description,Unit,1997,1998,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,"""00000""",United States *,,SAGDP2,1.0,...,All industry total,Millions of current dollars,8577552.0,9062817.0,...,18295019.0,18804913.0,19612102.0,20656516.0,21539982.0,21375281.0,23725645.0,26054614.0,27811517.0,29298013.0
96,"""01000""",Alabama,5,SAGDP2,1.0,...,All industry total,Millions of current dollars,105381.4,110838.8,...,203113.3,208824.3,216615.5,226263.8,234798.2,235859.0,260325.0,286873.3,309543.8,325345.1
188,"""02000""",Alaska,8,SAGDP2,1.0,...,All industry total,Millions of current dollars,25859.1,24387.8,...,51574.2,51121.8,53550.9,54762.0,54549.6,51861.7,59363.0,65682.5,68232.7,71567.2
280,"""04000""",Arizona,6,SAGDP2,1.0,...,All industry total,Millions of current dollars,132694.8,144393.2,...,298942.2,313787.1,333099.0,353671.0,375376.7,390503.2,438136.0,488722.2,530105.0,570088.6
372,"""05000""",Arkansas,5,SAGDP2,1.0,...,All industry total,Millions of current dollars,59925.0,62852.0,...,118573.6,120987.4,123882.6,129213.8,132625.8,136145.9,154261.8,167863.5,178114.8,188339.6

In [10]:
year_cols = [col for col in gdp.columns if col.isdigit()]
gdp = gdp[["GeoName"] + year_cols]

In [11]:
gdp.head()

,GeoName,1997,1998,1999,2000,2001,2002,2003,2004,2005,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,United States *,8577552.0,9062817.0,9631172.0,10250952.0,10581929.0,10929108.0,11456450.0,12217196.0,13039197.0,...,18295019.0,18804913.0,19612102.0,20656516.0,21539982.0,21375281.0,23725645.0,26054614.0,27811517.0,29298013.0
96,Alabama,105381.4,110838.8,116514.3,120522.6,123534.5,128380.9,135212.6,148379.1,158677.3,...,203113.3,208824.3,216615.5,226263.8,234798.2,235859.0,260325.0,286873.3,309543.8,325345.1
188,Alaska,25859.1,24387.8,24920.4,26934.0,28660.9,29884.5,32115.8,35389.5,40459.9,...,51574.2,51121.8,53550.9,54762.0,54549.6,51861.7,59363.0,65682.5,68232.7,71567.2
280,Arizona,132694.8,144393.2,156442.1,165735.6,172899.6,180844.5,194318.0,207246.3,227997.8,...,298942.2,313787.1,333099.0,353671.0,375376.7,390503.2,438136.0,488722.2,530105.0,570088.6
372,Arkansas,59925.0,62852.0,67279.0,69176.3,71099.6,74453.1,79009.7,85928.6,91133.4,...,118573.6,120987.4,123882.6,129213.8,132625.8,136145.9,154261.8,167863.5,178114.8,188339.6

In [12]:
gdp = gdp.rename(columns={"GeoName": "State"})

In [13]:
gdp.head()

,State,1997,1998,1999,2000,2001,2002,2003,2004,2005,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,United States *,8577552.0,9062817.0,9631172.0,10250952.0,10581929.0,10929108.0,11456450.0,12217196.0,13039197.0,...,18295019.0,18804913.0,19612102.0,20656516.0,21539982.0,21375281.0,23725645.0,26054614.0,27811517.0,29298013.0
96,Alabama,105381.4,110838.8,116514.3,120522.6,123534.5,128380.9,135212.6,148379.1,158677.3,...,203113.3,208824.3,216615.5,226263.8,234798.2,235859.0,260325.0,286873.3,309543.8,325345.1
188,Alaska,25859.1,24387.8,24920.4,26934.0,28660.9,29884.5,32115.8,35389.5,40459.9,...,51574.2,51121.8,53550.9,54762.0,54549.6,51861.7,59363.0,65682.5,68232.7,71567.2
280,Arizona,132694.8,144393.2,156442.1,165735.6,172899.6,180844.5,194318.0,207246.3,227997.8,...,298942.2,313787.1,333099.0,353671.0,375376.7,390503.2,438136.0,488722.2,530105.0,570088.6
372,Arkansas,59925.0,62852.0,67279.0,69176.3,71099.6,74453.1,79009.7,85928.6,91133.4,...,118573.6,120987.4,123882.6,129213.8,132625.8,136145.9,154261.8,167863.5,178114.8,188339.6

In [14]:
gdp = gdp[gdp["State"] != "United States *"]

In [15]:
gdp.head()

,State,1997,1998,1999,2000,2001,2002,2003,2004,2005,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
96,Alabama,105381.4,110838.8,116514.3,120522.6,123534.5,128380.9,135212.6,148379.1,158677.3,...,203113.3,208824.3,216615.5,226263.8,234798.2,235859.0,260325.0,286873.3,309543.8,325345.1
188,Alaska,25859.1,24387.8,24920.4,26934.0,28660.9,29884.5,32115.8,35389.5,40459.9,...,51574.2,51121.8,53550.9,54762.0,54549.6,51861.7,59363.0,65682.5,68232.7,71567.2
280,Arizona,132694.8,144393.2,156442.1,165735.6,172899.6,180844.5,194318.0,207246.3,227997.8,...,298942.2,313787.1,333099.0,353671.0,375376.7,390503.2,438136.0,488722.2,530105.0,570088.6
372,Arkansas,59925.0,62852.0,67279.0,69176.3,71099.6,74453.1,79009.7,85928.6,91133.4,...,118573.6,120987.4,123882.6,129213.8,132625.8,136145.9,154261.8,167863.5,178114.8,188339.6
464,California,1068048.6,1143672.5,1239773.5,1354791.3,1373270.8,1419321.8,1498578.0,1585081.4,1698858.4,...,2487156.4,2586485.2,2740550.3,2899530.9,3068629.7,3072927.6,3418256.1,3618289.7,3827007.3,4048108.1

In [16]:
gdp = gdp.reset_index(drop=True)

In [17]:
gdp.head()

,State,1997,1998,1999,2000,2001,2002,2003,2004,2005,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,Alabama,105381.4,110838.8,116514.3,120522.6,123534.5,128380.9,135212.6,148379.1,158677.3,...,203113.3,208824.3,216615.5,226263.8,234798.2,235859.0,260325.0,286873.3,309543.8,325345.1
1,Alaska,25859.1,24387.8,24920.4,26934.0,28660.9,29884.5,32115.8,35389.5,40459.9,...,51574.2,51121.8,53550.9,54762.0,54549.6,51861.7,59363.0,65682.5,68232.7,71567.2
2,Arizona,132694.8,144393.2,156442.1,165735.6,172899.6,180844.5,194318.0,207246.3,227997.8,...,298942.2,313787.1,333099.0,353671.0,375376.7,390503.2,438136.0,488722.2,530105.0,570088.6
3,Arkansas,59925.0,62852.0,67279.0,69176.3,71099.6,74453.1,79009.7,85928.6,91133.4,...,118573.6,120987.4,123882.6,129213.8,132625.8,136145.9,154261.8,167863.5,178114.8,188339.6
4,California,1068048.6,1143672.5,1239773.5,1354791.3,1373270.8,1419321.8,1498578.0,1585081.4,1698858.4,...,2487156.4,2586485.2,2740550.3,2899530.9,3068629.7,3072927.6,3418256.1,3618289.7,3827007.3,4048108.1

In [18]:
gdp = gdp.melt(id_vars="State", var_name="Year", value_name="GDP")

In [19]:
gdp.head()

        State  Year        GDP
0     Alabama  1997   105381.4
1      Alaska  1997    25859.1
2     Arizona  1997   132694.8
3    Arkansas  1997    59925.0
4  California  1997  1068048.6

In [20]:
gdp["Year"] = gdp["Year"].astype(int)
gdp["GDP"] = pd.to_numeric(gdp["GDP"], errors="coerce")

In [21]:
gdp.info()

<class 'pandas.DataFrame'>
RangeIndex: 1652 entries, 0 to 1651
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   State   1652 non-null   str
 1   Year    1652 non-null   int64
 2   GDP     1652 non-null   float64
dtypes: float64(1), int64(1), str(1)
memory usage: 38.8 KB

In [22]:
gdp.head()

        State  Year        GDP
0     Alabama  1997   105381.4
1      Alaska  1997    25859.1
2     Arizona  1997   132694.8
3    Arkansas  1997    59925.0
4  California  1997  1068048.6

In [23]:
gdp = gdp.sort_values(by=["State", "Year"])

In [24]:
gdp.head(30)

        State  Year       GDP
0     Alabama  1997  105381.4
59    Alabama  1998  110838.8
118   Alabama  1999  116514.3
177   Alabama  2000  120522.6
236   Alabama  2001  123534.5
295   Alabama  2002  128380.9
354   Alabama  2003  135212.6
413   Alabama  2004  148379.1
472   Alabama  2005  158677.3
531   Alabama  2006  166048.2
590   Alabama  2007  172247.0
649   Alabama  2008  174665.6
708   Alabama  2009  170876.5
767   Alabama  2010  177510.7
826   Alabama  2011  182896.7
885   Alabama  2012  188280.7
944   Alabama  2013  193981.5
1003  Alabama  2014  197064.4
1062  Alabama  2015  203113.3
1121  Alabama  2016  208824.3
1180  Alabama  2017  216615.5
1239  Alabama  2018  226263.8
1298  Alabama  2019  234798.2
1357  Alabama  2020  235859.0
1416  Alabama  2021  260325.0
1475  Alabama  2022  286873.3
1534  Alabama  2023  309543.8
1593  Alabama  2024  325345.1
1      Alaska  1997   25859.1
60     Alaska  1998   24387.8

In [25]:
gdp = gdp.reset_index(drop=True)

In [26]:
gdp.head()

     State  Year       GDP
0  Alabama  1997  105381.4
1  Alabama  1998  110838.8
2  Alabama  1999  116514.3
3  Alabama  2000  120522.6
4  Alabama  2001  123534.5

In [27]:
gdp.shape

(1652, 3)

In [28]:
gdp.columns

Index(['State', 'Year', 'GDP'], dtype='str')

In [29]:
gdp.info()

<class 'pandas.DataFrame'>
RangeIndex: 1652 entries, 0 to 1651
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   State   1652 non-null   str
 1   Year    1652 non-null   int64
 2   GDP     1652 non-null   float64
dtypes: float64(1), int64(1), str(1)
memory usage: 38.8 KB

In [30]:
gdp["State"].unique()

<StringArray>
[             'Alabama',               'Alaska',              'Arizona',
             'Arkansas',           'California',             'Colorado',
          'Connecticut',             'Delaware', 'District of Columbia',
             'Far West',              'Florida',              'Georgia',
          'Great Lakes',               'Hawaii',                'Idaho',
             'Illinois',              'Indiana',                 'Iowa',
               'Kansas',             'Kentucky',            'Louisiana',
                'Maine',             'Maryland',        'Massachusetts',
             'Michigan',              'Mideast',            'Minnesota',
          'Mississippi',             'Missouri',              'Montana',
             'Nebraska',               'Nevada',          'New England',
        'New Hampshire',           'New Jersey',           'New Mexico',
             'New York',       'North Carolina',         'North Dakota',
                 'Ohio',             'Oklahoma',               'Oregon',
         'Pennsylvania',               'Plains',         'Rhode Island',
       'Rocky Mountain',       'South Carolina',         'South Dakota',
            'Southeast',            'Southwest',            'Tennessee',
                'Texas',                 'Utah',              'Vermont',
             'Virginia',           'Washington',        'West Virginia',
            'Wisconsin',              'Wyoming']
Length: 59, dtype: str

In [31]:
regions = [
    "Far West", "Great Lakes", "Mideast", "New England",
    "Plains", "Rocky Mountain", "Southeast", "Southwest"
]

gdp = gdp[~gdp["State"].isin(regions)]

In [32]:
gdp["State"].unique()

<StringArray>
[             'Alabama',               'Alaska',              'Arizona',
             'Arkansas',           'California',             'Colorado',
          'Connecticut',             'Delaware', 'District of Columbia',
              'Florida',              'Georgia',               'Hawaii',
                'Idaho',             'Illinois',              'Indiana',
                 'Iowa',               'Kansas',             'Kentucky',
            'Louisiana',                'Maine',             'Maryland',
        'Massachusetts',             'Michigan',            'Minnesota',
          'Mississippi',             'Missouri',              'Montana',
             'Nebraska',               'Nevada',        'New Hampshire',
           'New Jersey',           'New Mexico',             'New York',
       'North Carolina',         'North Dakota',                 'Ohio',
             'Oklahoma',               'Oregon',         'Pennsylvania',
         'Rhode Island',       'South Carolina',         'South Dakota',
            'Tennessee',                'Texas',                 'Utah',
              'Vermont',             'Virginia',           'Washington',
        'West Virginia',            'Wisconsin',              'Wyoming']
Length: 51, dtype: str

In [33]:
gdp.head(20)

      State  Year       GDP
0   Alabama  1997  105381.4
1   Alabama  1998  110838.8
2   Alabama  1999  116514.3
3   Alabama  2000  120522.6
4   Alabama  2001  123534.5
5   Alabama  2002  128380.9
6   Alabama  2003  135212.6
7   Alabama  2004  148379.1
8   Alabama  2005  158677.3
9   Alabama  2006  166048.2
10  Alabama  2007  172247.0
11  Alabama  2008  174665.6
12  Alabama  2009  170876.5
13  Alabama  2010  177510.7
14  Alabama  2011  182896.7
15  Alabama  2012  188280.7
16  Alabama  2013  193981.5
17  Alabama  2014  197064.4
18  Alabama  2015  203113.3
19  Alabama  2016  208824.3

In [34]:
gdp.to_csv("../data/cleaned/gdp_clean.csv", index=False)

In [35]:
gdp.info()

<class 'pandas.DataFrame'>
Index: 1428 entries, 0 to 1651
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   State   1428 non-null   str
 1   Year    1428 non-null   int64
 2   GDP     1428 non-null   float64
dtypes: float64(1), int64(1), str(1)
memory usage: 44.6 KB

In [36]:
gdp.isna().sum()

State    0
Year     0
GDP      0
dtype: int64