In [12]:
import pandas as pd
import numpy as np

In [13]:
rincomepc_raw = pd.read_csv("../data/raw/real_income_per_capita.csv")

In [14]:
rincomepc = rincomepc_raw.copy()

In [15]:
rincomepc.head()

,GeoFIPS,GeoName,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,00000,United States,45816.0,44204.0,44808.0,45957.0,46796.0,46358.0,47661.0,49396.0,49828.0,51006.0,52242.0,53683.0,56514.0,59365.0,57104.0,58088.0,59195.0
1,01000,Alabama,42219.0,41966.0,41709.0,41819.0,41592.0,41325.0,41984.0,43809.0,43554.0,44481.0,46440.0,47130.0,50186.0,52875.0,50649.0,50902.0,52216.0
2,02000,Alaska,51647.0,50081.0,53163.0,54766.0,55096.0,53525.0,55480.0,56528.0,54411.0,54022.0,55403.0,56834.0,58522.0,57677.0,58413.0,58204.0,60272.0
3,04000,Arizona,38966.0,36634.0,37162.0,38403.0,39284.0,39204.0,40281.0,41960.0,42568.0,44279.0,45675.0,47236.0,50292.0,54424.0,50935.0,51960.0,52890.0
4,05000,Arkansas,40969.0,40953.0,40248.0,41264.0,42999.0,42386.0,44078.0,45415.0,45881.0,46861.0,48487.0,48246.0,51212.0,55184.0,53291.0,54094.0,55219.0

In [6]:
rincomepc.info()

<class 'pandas.DataFrame'>
RangeIndex: 55 entries, 0 to 54
Data columns (total 19 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   GeoFIPS  55 non-null     str
 1   GeoName  52 non-null     str
 2   2008     52 non-null     float64
 3   2009     52 non-null     float64
 4   2010     52 non-null     float64
 5   2011     52 non-null     float64
 6   2012     52 non-null     float64
 7   2013     52 non-null     float64
 8   2014     52 non-null     float64
 9   2015     52 non-null     float64
 10  2016     52 non-null     float64
 11  2017     52 non-null     float64
 12  2018     52 non-null     float64
 13  2019     52 non-null     float64
 14  2020     52 non-null     float64
 15  2021     52 non-null     float64
 16  2022     52 non-null     float64
 17  2023     52 non-null     float64
 18  2024     52 non-null     float64
dtypes: float64(17), str(2)
memory usage: 8.3 KB

In [17]:
rincomepc = rincomepc.drop(columns="GeoFIPS")

In [18]:
rincomepc = rincomepc.dropna()

In [19]:
rincomepc.head()

,GeoName,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,United States,45816.0,44204.0,44808.0,45957.0,46796.0,46358.0,47661.0,49396.0,49828.0,51006.0,52242.0,53683.0,56514.0,59365.0,57104.0,58088.0,59195.0
1,Alabama,42219.0,41966.0,41709.0,41819.0,41592.0,41325.0,41984.0,43809.0,43554.0,44481.0,46440.0,47130.0,50186.0,52875.0,50649.0,50902.0,52216.0
2,Alaska,51647.0,50081.0,53163.0,54766.0,55096.0,53525.0,55480.0,56528.0,54411.0,54022.0,55403.0,56834.0,58522.0,57677.0,58413.0,58204.0,60272.0
3,Arizona,38966.0,36634.0,37162.0,38403.0,39284.0,39204.0,40281.0,41960.0,42568.0,44279.0,45675.0,47236.0,50292.0,54424.0,50935.0,51960.0,52890.0
4,Arkansas,40969.0,40953.0,40248.0,41264.0,42999.0,42386.0,44078.0,45415.0,45881.0,46861.0,48487.0,48246.0,51212.0,55184.0,53291.0,54094.0,55219.0

In [20]:
rincomepc = rincomepc[rincomepc["GeoName"] != "United States"]

In [ ]:
rincomepc = rincomepc.rename(columns={"GeoName":"State"})

In [27]:
rincomepc.head()

,State,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
1,Alabama,42219.0,41966.0,41709.0,41819.0,41592.0,41325.0,41984.0,43809.0,43554.0,44481.0,46440.0,47130.0,50186.0,52875.0,50649.0,50902.0,52216.0
2,Alaska,51647.0,50081.0,53163.0,54766.0,55096.0,53525.0,55480.0,56528.0,54411.0,54022.0,55403.0,56834.0,58522.0,57677.0,58413.0,58204.0,60272.0
3,Arizona,38966.0,36634.0,37162.0,38403.0,39284.0,39204.0,40281.0,41960.0,42568.0,44279.0,45675.0,47236.0,50292.0,54424.0,50935.0,51960.0,52890.0
4,Arkansas,40969.0,40953.0,40248.0,41264.0,42999.0,42386.0,44078.0,45415.0,45881.0,46861.0,48487.0,48246.0,51212.0,55184.0,53291.0,54094.0,55219.0
5,California,43788.0,42377.0,43503.0,44844.0,46162.0,45826.0,47472.0,50054.0,51802.0,52569.0,53523.0,55931.0,59993.0,63373.0,59126.0,60100.0,63028.0

In [28]:
rincomepc = rincomepc.melt(id_vars="State", var_name="Year", value_name="Real_Income_pc")

In [29]:
rincomepc.head()

        State  Year  Real_Income_pc
0     Alabama  2008         42219.0
1      Alaska  2008         51647.0
2     Arizona  2008         38966.0
3    Arkansas  2008         40969.0
4  California  2008         43788.0

In [30]:
rincomepc.tail()

             State  Year  Real_Income_pc
862       Virginia  2024         61914.0
863     Washington  2024         64421.0
864  West Virginia  2024         50051.0
865      Wisconsin  2024         58273.0
866        Wyoming  2024         75501.0

In [31]:
rincomepc.isna().sum()

State             0
Year              0
Real_Income_pc    0
dtype: int64

In [32]:
rincomepc["State"].unique()

<StringArray>
[             'Alabama',               'Alaska',              'Arizona',
             'Arkansas',           'California',             'Colorado',
          'Connecticut',             'Delaware', 'District of Columbia',
              'Florida',              'Georgia',               'Hawaii',
                'Idaho',             'Illinois',              'Indiana',
                 'Iowa',               'Kansas',             'Kentucky',
            'Louisiana',                'Maine',             'Maryland',
        'Massachusetts',             'Michigan',            'Minnesota',
          'Mississippi',             'Missouri',              'Montana',
             'Nebraska',               'Nevada',        'New Hampshire',
           'New Jersey',           'New Mexico',             'New York',
       'North Carolina',         'North Dakota',                 'Ohio',
             'Oklahoma',               'Oregon',         'Pennsylvania',
         'Rhode Island',       'South Carolina',         'South Dakota',
            'Tennessee',                'Texas',                 'Utah',
              'Vermont',             'Virginia',           'Washington',
        'West Virginia',            'Wisconsin',              'Wyoming']
Length: 51, dtype: str

In [33]:
rincomepc = rincomepc.sort_values(by=["State", "Year"])

In [34]:
rincomepc.head()

       State  Year  Real_Income_pc
0    Alabama  2008         42219.0
51   Alabama  2009         41966.0
102  Alabama  2010         41709.0
153  Alabama  2011         41819.0
204  Alabama  2012         41592.0

In [35]:
rincomepc = rincomepc.reset_index(drop=True)

In [36]:
rincomepc.head()

     State  Year  Real_Income_pc
0  Alabama  2008         42219.0
1  Alabama  2009         41966.0
2  Alabama  2010         41709.0
3  Alabama  2011         41819.0
4  Alabama  2012         41592.0

In [38]:
rincomepc.info()

<class 'pandas.DataFrame'>
RangeIndex: 867 entries, 0 to 866
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   State           867 non-null    str
 1   Year            867 non-null    str
 2   Real_Income_pc  867 non-null    float64
dtypes: float64(1), str(2)
memory usage: 20.4 KB

In [39]:
rincomepc["Year"] = rincomepc["Year"].astype(int)

In [40]:
rincomepc.head()

     State  Year  Real_Income_pc
0  Alabama  2008         42219.0
1  Alabama  2009         41966.0
2  Alabama  2010         41709.0
3  Alabama  2011         41819.0
4  Alabama  2012         41592.0

In [41]:
rincomepc.tail()

       State  Year  Real_Income_pc
862  Wyoming  2020         67906.0
863  Wyoming  2021         71860.0
864  Wyoming  2022         73081.0
865  Wyoming  2023         75323.0
866  Wyoming  2024         75501.0

In [42]:
rincomepc.info()

<class 'pandas.DataFrame'>
RangeIndex: 867 entries, 0 to 866
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   State           867 non-null    str
 1   Year            867 non-null    int64
 2   Real_Income_pc  867 non-null    float64
dtypes: float64(1), int64(1), str(1)
memory usage: 20.4 KB

In [43]:
rincomepc.to_csv("../data/cleaned/real_income_pc_clean.csv", index=False)