In [2]:
import pandas as pd
import numpy as np

In [4]:
rpp_raw = pd.read_csv("../data/raw/regional_price_parity.csv")

In [5]:
rpp = rpp_raw.copy()

In [6]:
rpp.head()

,GeoFIPS,GeoName,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,00000,United States,100.000,100.000,100.000,100.000,100.000,100.000,100.000,100.000,100.000,100.000,100.000,100.000,100.000,100.000,100.000,100.000,100.000
1,01000,Alabama,88.901,87.786,89.783,90.011,90.559,90.324,90.175,89.741,90.609,90.065,87.378,88.303,87.569,88.062,88.021,89.097,88.823
2,02000,Alaska,103.878,106.147,103.099,103.274,102.548,102.052,102.386,103.287,104.073,104.833,104.565,103.041,101.339,104.907,102.101,103.297,102.359
3,04000,Arizona,102.504,102.865,100.558,99.083,98.050,98.441,97.944,97.865,98.622,97.915,97.381,97.779,99.203,96.600,99.992,100.742,100.677
4,05000,Arkansas,88.096,86.364,88.561,89.383,89.394,89.493,89.395,89.013,89.298,88.561,87.144,87.744,88.165,88.902,86.913,86.810,86.937

In [7]:
rpp = rpp.drop(columns="GeoFIPS")

In [8]:
rpp.head()

,GeoName,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,United States,100.000,100.000,100.000,100.000,100.000,100.000,100.000,100.000,100.000,100.000,100.000,100.000,100.000,100.000,100.000,100.000,100.000
1,Alabama,88.901,87.786,89.783,90.011,90.559,90.324,90.175,89.741,90.609,90.065,87.378,88.303,87.569,88.062,88.021,89.097,88.823
2,Alaska,103.878,106.147,103.099,103.274,102.548,102.052,102.386,103.287,104.073,104.833,104.565,103.041,101.339,104.907,102.101,103.297,102.359
3,Arizona,102.504,102.865,100.558,99.083,98.050,98.441,97.944,97.865,98.622,97.915,97.381,97.779,99.203,96.600,99.992,100.742,100.677
4,Arkansas,88.096,86.364,88.561,89.383,89.394,89.493,89.395,89.013,89.298,88.561,87.144,87.744,88.165,88.902,86.913,86.810,86.937

In [9]:
rpp.info()

<class 'pandas.DataFrame'>
RangeIndex: 54 entries, 0 to 53
Data columns (total 18 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   GeoName  52 non-null     str
 1   2008     52 non-null     float64
 2   2009     52 non-null     float64
 3   2010     52 non-null     float64
 4   2011     52 non-null     float64
 5   2012     52 non-null     float64
 6   2013     52 non-null     float64
 7   2014     52 non-null     float64
 8   2015     52 non-null     float64
 9   2016     52 non-null     float64
 10  2017     52 non-null     float64
 11  2018     52 non-null     float64
 12  2019     52 non-null     float64
 13  2020     52 non-null     float64
 14  2021     52 non-null     float64
 15  2022     52 non-null     float64
 16  2023     52 non-null     float64
 17  2024     52 non-null     float64
dtypes: float64(17), str(1)
memory usage: 7.7 KB

In [12]:
rpp.isna().sum()

GeoName    2
2008       2
2009       2
2010       2
2011       2
2012       2
2013       2
2014       2
2015       2
2016       2
2017       2
2018       2
2019       2
2020       2
2021       2
2022       2
2023       2
2024       2
dtype: int64

In [13]:
rpp.tail()

,GeoName,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
49,West Virginia,87.636,86.654,88.909,89.295,89.312,90.246,89.864,90.557,89.805,88.966,89.411,88.518,87.334,90.981,89.157,89.633,89.497
50,Wisconsin,93.159,94.116,94.723,93.742,94.312,93.890,93.799,93.287,93.173,93.531,94.028,94.476,92.666,93.309,92.401,93.220,94.095
51,Wyoming,95.291,96.618,95.473,97.618,96.265,97.347,97.404,96.941,97.747,97.146,92.372,94.107,91.836,91.440,91.767,91.551,92.691
52,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
rpp = rpp.dropna()

In [17]:
rpp = rpp.rename(columns={"GeoName" : "State"})

In [18]:
rpp.head()

,State,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,United States,100.000,100.000,100.000,100.000,100.000,100.000,100.000,100.000,100.000,100.000,100.000,100.000,100.000,100.000,100.000,100.000,100.000
1,Alabama,88.901,87.786,89.783,90.011,90.559,90.324,90.175,89.741,90.609,90.065,87.378,88.303,87.569,88.062,88.021,89.097,88.823
2,Alaska,103.878,106.147,103.099,103.274,102.548,102.052,102.386,103.287,104.073,104.833,104.565,103.041,101.339,104.907,102.101,103.297,102.359
3,Arizona,102.504,102.865,100.558,99.083,98.050,98.441,97.944,97.865,98.622,97.915,97.381,97.779,99.203,96.600,99.992,100.742,100.677
4,Arkansas,88.096,86.364,88.561,89.383,89.394,89.493,89.395,89.013,89.298,88.561,87.144,87.744,88.165,88.902,86.913,86.810,86.937

In [19]:
rpp = rpp[rpp["State"] != "United States"]

In [20]:
rpp.head()

,State,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
1,Alabama,88.901,87.786,89.783,90.011,90.559,90.324,90.175,89.741,90.609,90.065,87.378,88.303,87.569,88.062,88.021,89.097,88.823
2,Alaska,103.878,106.147,103.099,103.274,102.548,102.052,102.386,103.287,104.073,104.833,104.565,103.041,101.339,104.907,102.101,103.297,102.359
3,Arizona,102.504,102.865,100.558,99.083,98.050,98.441,97.944,97.865,98.622,97.915,97.381,97.779,99.203,96.600,99.992,100.742,100.677
4,Arkansas,88.096,86.364,88.561,89.383,89.394,89.493,89.395,89.013,89.298,88.561,87.144,87.744,88.165,88.902,86.913,86.810,86.937
5,California,111.220,110.696,109.703,109.503,109.666,109.667,109.926,110.685,109.956,110.998,111.882,111.134,111.944,111.918,112.591,112.195,110.720

In [21]:
rpp = rpp.melt(id_vars="State", var_name="Year", value_name="Regional Price Parity")

In [22]:
rpp.head()

        State  Year  Regional Price Parity
0     Alabama  2008                 88.901
1      Alaska  2008                103.878
2     Arizona  2008                102.504
3    Arkansas  2008                 88.096
4  California  2008                111.220

In [23]:
rpp["State"].unique()

<StringArray>
[             'Alabama',               'Alaska',              'Arizona',
             'Arkansas',           'California',             'Colorado',
          'Connecticut',             'Delaware', 'District of Columbia',
              'Florida',              'Georgia',               'Hawaii',
                'Idaho',             'Illinois',              'Indiana',
                 'Iowa',               'Kansas',             'Kentucky',
            'Louisiana',                'Maine',             'Maryland',
        'Massachusetts',             'Michigan',            'Minnesota',
          'Mississippi',             'Missouri',              'Montana',
             'Nebraska',               'Nevada',        'New Hampshire',
           'New Jersey',           'New Mexico',             'New York',
       'North Carolina',         'North Dakota',                 'Ohio',
             'Oklahoma',               'Oregon',         'Pennsylvania',
         'Rhode Island',       'South Carolina',         'South Dakota',
            'Tennessee',                'Texas',                 'Utah',
              'Vermont',             'Virginia',           'Washington',
        'West Virginia',            'Wisconsin',              'Wyoming']
Length: 51, dtype: str

In [27]:
rpp = rpp.sort_values(by=["State", "Year"])

In [29]:
rpp.head()

       State  Year  Regional Price Parity
0    Alabama  2008                 88.901
51   Alabama  2009                 87.786
102  Alabama  2010                 89.783
153  Alabama  2011                 90.011
204  Alabama  2012                 90.559

In [30]:
rpp = rpp.reset_index(drop=True)

In [31]:
rpp.head()

     State  Year  Regional Price Parity
0  Alabama  2008                 88.901
1  Alabama  2009                 87.786
2  Alabama  2010                 89.783
3  Alabama  2011                 90.011
4  Alabama  2012                 90.559

In [32]:
rpp.tail()

       State  Year  Regional Price Parity
862  Wyoming  2020                 91.836
863  Wyoming  2021                 91.440
864  Wyoming  2022                 91.767
865  Wyoming  2023                 91.551
866  Wyoming  2024                 92.691

In [33]:
rpp.info()

<class 'pandas.DataFrame'>
RangeIndex: 867 entries, 0 to 866
Data columns (total 3 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   State                  867 non-null    str
 1   Year                   867 non-null    str
 2   Regional Price Parity  867 non-null    float64
dtypes: float64(1), str(2)
memory usage: 20.4 KB

In [35]:
rpp["Year"] = rpp["Year"].astype(int)

In [36]:
rpp = rpp.rename(columns={"Regional Price Parity" : "RPP"})

In [37]:
rpp.info()

<class 'pandas.DataFrame'>
RangeIndex: 867 entries, 0 to 866
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   State   867 non-null    str
 1   Year    867 non-null    int64
 2   RPP     867 non-null    float64
dtypes: float64(1), int64(1), str(1)
memory usage: 20.4 KB

In [38]:
sorted(rpp["State"].unique())

['Alabama',
 'Alaska',
 'Arizona',
 'Arkansas',
 'California',
 'Colorado',
 'Connecticut',
 'Delaware',
 'District of Columbia',
 'Florida',
 'Georgia',
 'Hawaii',
 'Idaho',
 'Illinois',
 'Indiana',
 'Iowa',
 'Kansas',
 'Kentucky',
 'Louisiana',
 'Maine',
 'Maryland',
 'Massachusetts',
 'Michigan',
 'Minnesota',
 'Mississippi',
 'Missouri',
 'Montana',
 'Nebraska',
 'Nevada',
 'New Hampshire',
 'New Jersey',
 'New Mexico',
 'New York',
 'North Carolina',
 'North Dakota',
 'Ohio',
 'Oklahoma',
 'Oregon',
 'Pennsylvania',
 'Rhode Island',
 'South Carolina',
 'South Dakota',
 'Tennessee',
 'Texas',
 'Utah',
 'Vermont',
 'Virginia',
 'Washington',
 'West Virginia',
 'Wisconsin',
 'Wyoming']

In [39]:
rpp["Year"].min(), rpp["Year"].max()

(np.int64(2008), np.int64(2024))

In [40]:
sorted(rpp["Year"].unique())

[np.int64(2008),
 np.int64(2009),
 np.int64(2010),
 np.int64(2011),
 np.int64(2012),
 np.int64(2013),
 np.int64(2014),
 np.int64(2015),
 np.int64(2016),
 np.int64(2017),
 np.int64(2018),
 np.int64(2019),
 np.int64(2020),
 np.int64(2021),
 np.int64(2022),
 np.int64(2023),
 np.int64(2024)]

In [41]:
rpp.shape

(867, 3)

In [42]:
rpp["RPP"].describe()

count    867.000000
mean      97.503449
std        6.936859
min       85.018000
25%       91.842000
50%       96.717000
75%      102.414500
max      114.242000
Name: RPP, dtype: float64

In [43]:
rpp.to_csv("../data/cleaned/regional_price_parity_clean.csv", index=False)