In [17]:
import pandas as pd
import numpy as np

In [18]:
df_employment_raw = pd.read_csv("../data/raw/employment.csv")
df_employment = df_employment_raw.copy()

In [19]:
df_employment.head()

,GeoFIPS,GeoName,1998,1999,2000,2001,2002,2003,2004,2005,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,00000,United States,158481200.0,161531300.0,165370800.0,165522200.0,165095100.0,165921500.0,168839700.0,172338400.0,...,193425900.0,196394100.0,200292200.0,201622200.0,195278600.0,202705100.0,210466200.0,216347200.0,218181200.0,(NA)
1,01000,Alabama,2361892.0,2378217.0,2392225.0,2376053.0,2364829.0,2371429.0,2425650.0,2486829.0,...,2619761.0,2649222.0,2692424.0,2712014.0,2670980.0,2769117.0,2857149.0,2931413.0,2969241.0,(NA)
2,02000,Alaska,382166.0,381307.0,389734.0,394565.0,402192.0,405625.0,413869.0,421422.0,...,457142.0,455550.0,454776.0,454794.0,430889.0,443016.0,454025.0,467104.0,474188.0,(NA)
3,04000,Arizona,2616288.0,2695892.0,2801510.0,2829002.0,2847070.0,2917095.0,3041449.0,3219799.0,...,3644791.0,3740747.0,3854741.0,3929587.0,3919887.0,4085773.0,4250495.0,4404247.0,4457506.0,(NA)
4,05000,Arkansas,1445536.0,1460374.0,1482449.0,1482587.0,1478920.0,1482026.0,1505086.0,1537671.0,...,1629734.0,1639903.0,1658212.0,1663305.0,1639041.0,1684580.0,1744586.0,1789021.0,1805358.0,(NA)

In [20]:
df_employment = df_employment[df_employment["GeoName"] != "United States"]

In [21]:
df_employment.head()

,GeoFIPS,GeoName,1998,1999,2000,2001,2002,2003,2004,2005,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
1,01000,Alabama,2361892.0,2378217.0,2392225.0,2376053.0,2364829.0,2371429.0,2425650.0,2486829.0,...,2619761.0,2649222.0,2692424.0,2712014.0,2670980.0,2769117.0,2857149.0,2931413.0,2969241.0,(NA)
2,02000,Alaska,382166.0,381307.0,389734.0,394565.0,402192.0,405625.0,413869.0,421422.0,...,457142.0,455550.0,454776.0,454794.0,430889.0,443016.0,454025.0,467104.0,474188.0,(NA)
3,04000,Arizona,2616288.0,2695892.0,2801510.0,2829002.0,2847070.0,2917095.0,3041449.0,3219799.0,...,3644791.0,3740747.0,3854741.0,3929587.0,3919887.0,4085773.0,4250495.0,4404247.0,4457506.0,(NA)
4,05000,Arkansas,1445536.0,1460374.0,1482449.0,1482587.0,1478920.0,1482026.0,1505086.0,1537671.0,...,1629734.0,1639903.0,1658212.0,1663305.0,1639041.0,1684580.0,1744586.0,1789021.0,1805358.0,(NA)
5,06000,California,18432865.0,18852334.0,19228895.0,19341458.0,19358251.0,19478732.0,19784214.0,20126936.0,...,23177961.0,23548874.0,24077466.0,24224461.0,23156746.0,23932245.0,24941794.0,25260641.0,25583169.0,(NA)

In [22]:
df_employment = df_employment.drop(columns="GeoFIPS")

In [23]:
df_employment.info()

<class 'pandas.DataFrame'>
RangeIndex: 54 entries, 1 to 54
Data columns (total 29 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   GeoName  51 non-null     str
 1   1998     51 non-null     float64
 2   1999     51 non-null     float64
 3   2000     51 non-null     float64
 4   2001     51 non-null     float64
 5   2002     51 non-null     float64
 6   2003     51 non-null     float64
 7   2004     51 non-null     float64
 8   2005     51 non-null     float64
 9   2006     51 non-null     float64
 10  2007     51 non-null     float64
 11  2008     51 non-null     float64
 12  2009     51 non-null     float64
 13  2010     51 non-null     float64
 14  2011     51 non-null     float64
 15  2012     51 non-null     float64
 16  2013     51 non-null     float64
 17  2014     51 non-null     float64
 18  2015     51 non-null     float64
 19  2016     51 non-null     float64
 20  2017     51 non-null     float64
 21  2018     51 non-null     float64
 22  2019     51 non-null     float64
 23  2020     51 non-null     float64
 24  2021     51 non-null     float64
 25  2022     51 non-null     float64
 26  2023     51 non-null     float64
 27  2024     51 non-null     float64
 28  2025     51 non-null     str
dtypes: float64(27), str(2)
memory usage: 12.4 KB

In [24]:
for i in range(1998, 2008):
    df_employment = df_employment.drop(columns=str(i))

In [25]:
df_employment.head()

,GeoName,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
1,Alabama,2582600.0,2479511.0,2460305.0,2497974.0,2503656.0,2523020.0,2552256.0,2587641.0,2619761.0,2649222.0,2692424.0,2712014.0,2670980.0,2769117.0,2857149.0,2931413.0,2969241.0,(NA)
2,Alaska,443602.0,442505.0,443940.0,450420.0,459282.0,461205.0,461371.0,461707.0,457142.0,455550.0,454776.0,454794.0,430889.0,443016.0,454025.0,467104.0,474188.0,(NA)
3,Arizona,3402806.0,3228516.0,3181563.0,3239037.0,3295532.0,3371101.0,3448146.0,3547647.0,3644791.0,3740747.0,3854741.0,3929587.0,3919887.0,4085773.0,4250495.0,4404247.0,4457506.0,(NA)
4,Arkansas,1579250.0,1542904.0,1541250.0,1561929.0,1565109.0,1569358.0,1587408.0,1610799.0,1629734.0,1639903.0,1658212.0,1663305.0,1639041.0,1684580.0,1744586.0,1789021.0,1805358.0,(NA)
5,California,20654365.0,19837727.0,19642544.0,19986185.0,20666919.0,21318697.0,21996861.0,22687175.0,23177961.0,23548874.0,24077466.0,24224461.0,23156746.0,23932245.0,24941794.0,25260641.0,25583169.0,(NA)

In [26]:
df_employment = df_employment.rename(columns={"GeoName":"State"})

In [27]:
df_employment = df_employment.melt(id_vars="State", var_name="Year", value_name="Employment")

In [28]:
df_employment.head()

        State  Year  Employment
0     Alabama  2008   2582600.0
1      Alaska  2008    443602.0
2     Arizona  2008   3402806.0
3    Arkansas  2008   1579250.0
4  California  2008  20654365.0

In [30]:
df_employment = df_employment.dropna()

In [35]:
sorted(df_employment["State"].unique())

['Alabama',
 'Alaska',
 'Arizona',
 'Arkansas',
 'California',
 'Colorado',
 'Connecticut',
 'Delaware',
 'District of Columbia',
 'Florida',
 'Georgia',
 'Hawaii',
 'Idaho',
 'Illinois',
 'Indiana',
 'Iowa',
 'Kansas',
 'Kentucky',
 'Louisiana',
 'Maine',
 'Maryland',
 'Massachusetts',
 'Michigan',
 'Minnesota',
 'Mississippi',
 'Missouri',
 'Montana',
 'Nebraska',
 'Nevada',
 'New Hampshire',
 'New Jersey',
 'New Mexico',
 'New York',
 'North Carolina',
 'North Dakota',
 'Ohio',
 'Oklahoma',
 'Oregon',
 'Pennsylvania',
 'Rhode Island',
 'South Carolina',
 'South Dakota',
 'Tennessee',
 'Texas',
 'Utah',
 'Vermont',
 'Virginia',
 'Washington',
 'West Virginia',
 'Wisconsin',
 'Wyoming']

In [36]:
df_employment.info()

<class 'pandas.DataFrame'>
Index: 918 entries, 0 to 968
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   State       918 non-null    str
 1   Year        918 non-null    str
 2   Employment  918 non-null    object
dtypes: object(1), str(2)
memory usage: 28.7+ KB

In [37]:
df_employment["Year"] = df_employment["Year"].astype(int)

In [44]:
df_employment["State"].nunique()

51

In [45]:
df_employment = df_employment.reset_index(drop=True)

In [47]:
df_employment = df_employment.sort_values(by=["State", "Year"])

In [48]:
df_employment.head(20)

       State  Year Employment
0    Alabama  2008  2582600.0
51   Alabama  2009  2479511.0
102  Alabama  2010  2460305.0
153  Alabama  2011  2497974.0
204  Alabama  2012  2503656.0
255  Alabama  2013  2523020.0
306  Alabama  2014  2552256.0
357  Alabama  2015  2587641.0
408  Alabama  2016  2619761.0
459  Alabama  2017  2649222.0
510  Alabama  2018  2692424.0
561  Alabama  2019  2712014.0
612  Alabama  2020  2670980.0
663  Alabama  2021  2769117.0
714  Alabama  2022  2857149.0
765  Alabama  2023  2931413.0
816  Alabama  2024  2969241.0
867  Alabama  2025       (NA)
1     Alaska  2008   443602.0
52    Alaska  2009   442505.0

In [49]:
df_employment = df_employment[df_employment["Year"] != 2025]

In [50]:
df_employment = df_employment.reset_index(drop=True)

In [51]:
df_employment.head(20)

      State  Year Employment
0   Alabama  2008  2582600.0
1   Alabama  2009  2479511.0
2   Alabama  2010  2460305.0
3   Alabama  2011  2497974.0
4   Alabama  2012  2503656.0
5   Alabama  2013  2523020.0
6   Alabama  2014  2552256.0
7   Alabama  2015  2587641.0
8   Alabama  2016  2619761.0
9   Alabama  2017  2649222.0
10  Alabama  2018  2692424.0
11  Alabama  2019  2712014.0
12  Alabama  2020  2670980.0
13  Alabama  2021  2769117.0
14  Alabama  2022  2857149.0
15  Alabama  2023  2931413.0
16  Alabama  2024  2969241.0
17   Alaska  2008   443602.0
18   Alaska  2009   442505.0
19   Alaska  2010   443940.0

In [52]:
df_employment.tail(20)

         State  Year Employment
847  Wisconsin  2022  3767253.0
848  Wisconsin  2023  3841837.0
849  Wisconsin  2024  3867941.0
850    Wyoming  2008   398989.0
851    Wyoming  2009   387490.0
852    Wyoming  2010   385075.0
853    Wyoming  2011   390340.0
854    Wyoming  2012   396724.0
855    Wyoming  2013   400510.0
856    Wyoming  2014   406401.0
857    Wyoming  2015   406045.0
858    Wyoming  2016   398144.0
859    Wyoming  2017   398968.0
860    Wyoming  2018   404591.0
861    Wyoming  2019   407870.0
862    Wyoming  2020   401439.0
863    Wyoming  2021   419797.0
864    Wyoming  2022   430968.0
865    Wyoming  2023   449620.0
866    Wyoming  2024   447255.0

In [53]:
df_employment.to_csv("../data/cleaned/employment_clean.csv", index=False)