In [19]:
import pandas as pd
import numpy as np

In [20]:
raw_pop = pd.read_csv('../data/raw/population.csv')
pop = raw_pop.copy()

In [21]:
pop.head()

,GeoFIPS,GeoName,1929,1930,1931,1932,1933,1934,1935,1936,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,00000,United States,121769000,123075000,124038000,124839000,125580000,126372000,127251000,128054000,...,324353340.0,326608609.0,328529577.0,330226227.0,331578104.0,332100166.0,333996304.0,336755052.0,340003797.0,341784857.0
1,01000,Alabama,2644000,2647000,2649000,2653000,2661000,2685000,2719000,2743000,...,4931579.0,4953096.0,4977088.0,5003778.0,5032962.0,5050058.0,5076868.0,5117850.0,5163055.0,5193088.0
2,02000,Alaska *,(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),...,743397.0,741937.0,737710.0,734820.0,732906.0,734590.0,733659.0,734654.0,736537.0,737270.0
3,04000,Arizona,430000,434000,429000,426000,426000,428000,434000,443000,...,6793278.0,6872380.0,6964300.0,7067695.0,7186647.0,7274022.0,7370065.0,7452073.0,7556424.0,7623818.0
4,05000,Arkansas,1852000,1859000,1848000,1836000,1854000,1878000,1890000,1892000,...,2980475.0,2990702.0,2997195.0,3004206.0,3014399.0,3027127.0,3047429.0,3069856.0,3096080.0,3114791.0

In [22]:
pop = pop.drop(columns=['GeoFIPS'])

In [23]:
pop = pop.rename(columns={'GeoName': 'State'})

In [24]:
pop.head()

,State,1929,1930,1931,1932,1933,1934,1935,1936,1937,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,United States,121769000,123075000,124038000,124839000,125580000,126372000,127251000,128054000,128822000,...,324353340.0,326608609.0,328529577.0,330226227.0,331578104.0,332100166.0,333996304.0,336755052.0,340003797.0,341784857.0
1,Alabama,2644000,2647000,2649000,2653000,2661000,2685000,2719000,2743000,2762000,...,4931579.0,4953096.0,4977088.0,5003778.0,5032962.0,5050058.0,5076868.0,5117850.0,5163055.0,5193088.0
2,Alaska *,(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),...,743397.0,741937.0,737710.0,734820.0,732906.0,734590.0,733659.0,734654.0,736537.0,737270.0
3,Arizona,430000,434000,429000,426000,426000,428000,434000,443000,453000,...,6793278.0,6872380.0,6964300.0,7067695.0,7186647.0,7274022.0,7370065.0,7452073.0,7556424.0,7623818.0
4,Arkansas,1852000,1859000,1848000,1836000,1854000,1878000,1890000,1892000,1903000,...,2980475.0,2990702.0,2997195.0,3004206.0,3014399.0,3027127.0,3047429.0,3069856.0,3096080.0,3114791.0

In [25]:
cols_to_drop = [str(i) for i in range(1929, 2008)]
pop = pop.drop(columns=cols_to_drop)

In [26]:
pop.head()

,State,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,United States,304093966.0,306771529.0,309378227.0,311839461.0,314339099.0,316726282.0,319257560.0,321815121.0,324353340.0,326608609.0,328529577.0,330226227.0,331578104.0,332100166.0,333996304.0,336755052.0,340003797.0,341784857.0
1,Alabama,4718206.0,4757938.0,4788095.0,4812576.0,4839947.0,4865253.0,4887757.0,4909177.0,4931579.0,4953096.0,4977088.0,5003778.0,5032962.0,5050058.0,5076868.0,5117850.0,5163055.0,5193088.0
2,Alaska *,687455.0,698895.0,714015.0,722513.0,731106.0,738054.0,737634.0,739120.0,743397.0,741937.0,737710.0,734820.0,732906.0,734590.0,733659.0,734654.0,736537.0,737270.0
3,Arizona,6280362.0,6343154.0,6401304.0,6443158.0,6501800.0,6555926.0,6629890.0,6705607.0,6793278.0,6872380.0,6964300.0,7067695.0,7186647.0,7274022.0,7370065.0,7452073.0,7556424.0,7623818.0
4,Arkansas,2874554.0,2896843.0,2921546.0,2938773.0,2948793.0,2954563.0,2961050.0,2970210.0,2980475.0,2990702.0,2997195.0,3004206.0,3014399.0,3027127.0,3047429.0,3069856.0,3096080.0,3114791.0

In [28]:
pop = pop[pop['State'] != 'United States']

In [29]:
pop.head()

,State,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
1,Alabama,4718206.0,4757938.0,4788095.0,4812576.0,4839947.0,4865253.0,4887757.0,4909177.0,4931579.0,4953096.0,4977088.0,5003778.0,5032962.0,5050058.0,5076868.0,5117850.0,5163055.0,5193088.0
2,Alaska *,687455.0,698895.0,714015.0,722513.0,731106.0,738054.0,737634.0,739120.0,743397.0,741937.0,737710.0,734820.0,732906.0,734590.0,733659.0,734654.0,736537.0,737270.0
3,Arizona,6280362.0,6343154.0,6401304.0,6443158.0,6501800.0,6555926.0,6629890.0,6705607.0,6793278.0,6872380.0,6964300.0,7067695.0,7186647.0,7274022.0,7370065.0,7452073.0,7556424.0,7623818.0
4,Arkansas,2874554.0,2896843.0,2921546.0,2938773.0,2948793.0,2954563.0,2961050.0,2970210.0,2980475.0,2990702.0,2997195.0,3004206.0,3014399.0,3027127.0,3047429.0,3069856.0,3096080.0,3114791.0
5,California,36604337.0,36961229.0,37322523.0,37651212.0,37971412.0,38292557.0,38637421.0,38966939.0,39223789.0,39424315.0,39535920.0,39547995.0,39527808.0,39152927.0,39125347.0,39181667.0,39364774.0,39355309.0

In [32]:
pop['State'].unique

<bound method Series.unique of 1                  Alabama
2                 Alaska *
3                  Arizona
4                 Arkansas
5               California
6                 Colorado
7              Connecticut
8                 Delaware
9     District of Columbia
10                 Florida
11                 Georgia
12                Hawaii *
13                   Idaho
14                Illinois
15                 Indiana
16                    Iowa
17                  Kansas
18                Kentucky
19               Louisiana
20                   Maine
21                Maryland
22           Massachusetts
23                Michigan
24               Minnesota
25             Mississippi
26                Missouri
27                 Montana
28                Nebraska
29                  Nevada
30           New Hampshire
31              New Jersey
32              New Mexico
33                New York
34          North Carolina
35            North Dakota
36                    Ohio
37                Oklahoma
38                  Oregon
39            Pennsylvania
40            Rhode Island
41          South Carolina
42            South Dakota
43               Tennessee
44                   Texas
45                    Utah
46                 Vermont
47                Virginia
48              Washington
49           West Virginia
50               Wisconsin
51                 Wyoming
52             New England
53                 Mideast
54             Great Lakes
55                  Plains
56               Southeast
57               Southwest
58          Rocky Mountain
59              Far West *
Name: State, dtype: str>

In [31]:
pop = pop.dropna()

In [34]:
pop["State"] = pop["State"].str.replace(" *", "", regex=False)

In [35]:
pop.head()

,State,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
1,Alabama,4718206.0,4757938.0,4788095.0,4812576.0,4839947.0,4865253.0,4887757.0,4909177.0,4931579.0,4953096.0,4977088.0,5003778.0,5032962.0,5050058.0,5076868.0,5117850.0,5163055.0,5193088.0
2,Alaska,687455.0,698895.0,714015.0,722513.0,731106.0,738054.0,737634.0,739120.0,743397.0,741937.0,737710.0,734820.0,732906.0,734590.0,733659.0,734654.0,736537.0,737270.0
3,Arizona,6280362.0,6343154.0,6401304.0,6443158.0,6501800.0,6555926.0,6629890.0,6705607.0,6793278.0,6872380.0,6964300.0,7067695.0,7186647.0,7274022.0,7370065.0,7452073.0,7556424.0,7623818.0
4,Arkansas,2874554.0,2896843.0,2921546.0,2938773.0,2948793.0,2954563.0,2961050.0,2970210.0,2980475.0,2990702.0,2997195.0,3004206.0,3014399.0,3027127.0,3047429.0,3069856.0,3096080.0,3114791.0
5,California,36604337.0,36961229.0,37322523.0,37651212.0,37971412.0,38292557.0,38637421.0,38966939.0,39223789.0,39424315.0,39535920.0,39547995.0,39527808.0,39152927.0,39125347.0,39181667.0,39364774.0,39355309.0

In [36]:
regions = [
    "Far West", "Great Lakes", "Mideast", "New England",
    "Plains", "Rocky Mountain", "Southeast", "Southwest"
]

pop = pop[~pop["State"].isin(regions)]

In [37]:
pop.head()

,State,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
1,Alabama,4718206.0,4757938.0,4788095.0,4812576.0,4839947.0,4865253.0,4887757.0,4909177.0,4931579.0,4953096.0,4977088.0,5003778.0,5032962.0,5050058.0,5076868.0,5117850.0,5163055.0,5193088.0
2,Alaska,687455.0,698895.0,714015.0,722513.0,731106.0,738054.0,737634.0,739120.0,743397.0,741937.0,737710.0,734820.0,732906.0,734590.0,733659.0,734654.0,736537.0,737270.0
3,Arizona,6280362.0,6343154.0,6401304.0,6443158.0,6501800.0,6555926.0,6629890.0,6705607.0,6793278.0,6872380.0,6964300.0,7067695.0,7186647.0,7274022.0,7370065.0,7452073.0,7556424.0,7623818.0
4,Arkansas,2874554.0,2896843.0,2921546.0,2938773.0,2948793.0,2954563.0,2961050.0,2970210.0,2980475.0,2990702.0,2997195.0,3004206.0,3014399.0,3027127.0,3047429.0,3069856.0,3096080.0,3114791.0
5,California,36604337.0,36961229.0,37322523.0,37651212.0,37971412.0,38292557.0,38637421.0,38966939.0,39223789.0,39424315.0,39535920.0,39547995.0,39527808.0,39152927.0,39125347.0,39181667.0,39364774.0,39355309.0

In [38]:
pop["State"].unique

<bound method Series.unique of 1                  Alabama
2                   Alaska
3                  Arizona
4                 Arkansas
5               California
6                 Colorado
7              Connecticut
8                 Delaware
9     District of Columbia
10                 Florida
11                 Georgia
12                  Hawaii
13                   Idaho
14                Illinois
15                 Indiana
16                    Iowa
17                  Kansas
18                Kentucky
19               Louisiana
20                   Maine
21                Maryland
22           Massachusetts
23                Michigan
24               Minnesota
25             Mississippi
26                Missouri
27                 Montana
28                Nebraska
29                  Nevada
30           New Hampshire
31              New Jersey
32              New Mexico
33                New York
34          North Carolina
35            North Dakota
36                    Ohio
37                Oklahoma
38                  Oregon
39            Pennsylvania
40            Rhode Island
41          South Carolina
42            South Dakota
43               Tennessee
44                   Texas
45                    Utah
46                 Vermont
47                Virginia
48              Washington
49           West Virginia
50               Wisconsin
51                 Wyoming
Name: State, dtype: str>

In [39]:
pop.info()

<class 'pandas.DataFrame'>
RangeIndex: 51 entries, 1 to 51
Data columns (total 19 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   State   51 non-null     str
 1   2008    51 non-null     float64
 2   2009    51 non-null     float64
 3   2010    51 non-null     float64
 4   2011    51 non-null     float64
 5   2012    51 non-null     float64
 6   2013    51 non-null     float64
 7   2014    51 non-null     float64
 8   2015    51 non-null     float64
 9   2016    51 non-null     float64
 10  2017    51 non-null     float64
 11  2018    51 non-null     float64
 12  2019    51 non-null     float64
 13  2020    51 non-null     float64
 14  2021    51 non-null     float64
 15  2022    51 non-null     float64
 16  2023    51 non-null     float64
 17  2024    51 non-null     float64
 18  2025    51 non-null     float64
dtypes: float64(18), str(1)
memory usage: 7.7 KB

In [40]:
pop = pop.melt(id_vars="State", var_name="Year", value_name="Population")

In [41]:
pop.head()

        State  Year  Population
0     Alabama  2008   4718206.0
1      Alaska  2008    687455.0
2     Arizona  2008   6280362.0
3    Arkansas  2008   2874554.0
4  California  2008  36604337.0

In [42]:
pop = pop.sort_values(by=["State", "Year"])

In [47]:
pop['Year'] = pop['Year'].astype(int)
pop['Population'] = pop['Population'].astype(int)

In [46]:
pop.head()

       State  Year  Population
0    Alabama  2008     4718206
51   Alabama  2009     4757938
102  Alabama  2010     4788095
153  Alabama  2011     4812576
204  Alabama  2012     4839947

In [49]:
pop.info()

<class 'pandas.DataFrame'>
Index: 918 entries, 0 to 917
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   State       918 non-null    str
 1   Year        918 non-null    int64
 2   Population  918 non-null    int64
dtypes: int64(2), str(1)
memory usage: 28.7 KB

In [50]:
pop.head(20)

       State  Year  Population
0    Alabama  2008     4718206
51   Alabama  2009     4757938
102  Alabama  2010     4788095
153  Alabama  2011     4812576
204  Alabama  2012     4839947
255  Alabama  2013     4865253
306  Alabama  2014     4887757
357  Alabama  2015     4909177
408  Alabama  2016     4931579
459  Alabama  2017     4953096
510  Alabama  2018     4977088
561  Alabama  2019     5003778
612  Alabama  2020     5032962
663  Alabama  2021     5050058
714  Alabama  2022     5076868
765  Alabama  2023     5117850
816  Alabama  2024     5163055
867  Alabama  2025     5193088
1     Alaska  2008      687455
52    Alaska  2009      698895

In [51]:
pop = pop.reset_index(drop=True)

In [52]:
pop.head(20)

      State  Year  Population
0   Alabama  2008     4718206
1   Alabama  2009     4757938
2   Alabama  2010     4788095
3   Alabama  2011     4812576
4   Alabama  2012     4839947
5   Alabama  2013     4865253
6   Alabama  2014     4887757
7   Alabama  2015     4909177
8   Alabama  2016     4931579
9   Alabama  2017     4953096
10  Alabama  2018     4977088
11  Alabama  2019     5003778
12  Alabama  2020     5032962
13  Alabama  2021     5050058
14  Alabama  2022     5076868
15  Alabama  2023     5117850
16  Alabama  2024     5163055
17  Alabama  2025     5193088
18   Alaska  2008      687455
19   Alaska  2009      698895

In [56]:
pop = pop[pop["Year"] != 2025]

In [57]:
pop.head(20)

      State  Year  Population
0   Alabama  2008     4718206
1   Alabama  2009     4757938
2   Alabama  2010     4788095
3   Alabama  2011     4812576
4   Alabama  2012     4839947
5   Alabama  2013     4865253
6   Alabama  2014     4887757
7   Alabama  2015     4909177
8   Alabama  2016     4931579
9   Alabama  2017     4953096
10  Alabama  2018     4977088
11  Alabama  2019     5003778
12  Alabama  2020     5032962
13  Alabama  2021     5050058
14  Alabama  2022     5076868
15  Alabama  2023     5117850
16  Alabama  2024     5163055
18   Alaska  2008      687455
19   Alaska  2009      698895
20   Alaska  2010      714015

In [59]:
pop.to_csv('../data/cleaned/population_cleaned.csv', index=False)