In [1]:
import numpy as np
import pandas as pd

In [2]:
raw_employment = pd.read_csv("../data/cleaned/employment_clean.csv")
employment_pc = raw_employment.copy()

raw_population = pd.read_csv("../data/cleaned/population_cleaned.csv")
population = raw_population.copy()

In [3]:
employment_pc.head(20)

      State  Year  Employment
0   Alabama  2008   2582600.0
1   Alabama  2009   2479511.0
2   Alabama  2010   2460305.0
3   Alabama  2011   2497974.0
4   Alabama  2012   2503656.0
5   Alabama  2013   2523020.0
6   Alabama  2014   2552256.0
7   Alabama  2015   2587641.0
8   Alabama  2016   2619761.0
9   Alabama  2017   2649222.0
10  Alabama  2018   2692424.0
11  Alabama  2019   2712014.0
12  Alabama  2020   2670980.0
13  Alabama  2021   2769117.0
14  Alabama  2022   2857149.0
15  Alabama  2023   2931413.0
16  Alabama  2024   2969241.0
17   Alaska  2008    443602.0
18   Alaska  2009    442505.0
19   Alaska  2010    443940.0

In [4]:
population.head(20)

      State  Year  Population
0   Alabama  2008     4718206
1   Alabama  2009     4757938
2   Alabama  2010     4788095
3   Alabama  2011     4812576
4   Alabama  2012     4839947
5   Alabama  2013     4865253
6   Alabama  2014     4887757
7   Alabama  2015     4909177
8   Alabama  2016     4931579
9   Alabama  2017     4953096
10  Alabama  2018     4977088
11  Alabama  2019     5003778
12  Alabama  2020     5032962
13  Alabama  2021     5050058
14  Alabama  2022     5076868
15  Alabama  2023     5117850
16  Alabama  2024     5163055
17   Alaska  2008      687455
18   Alaska  2009      698895
19   Alaska  2010      714015

In [5]:
employment_pc = employment_pc.merge(population[['State', 'Year', 'Population']], on=['State', 'Year'], how='left')
employment_pc["Employment"] = employment_pc["Employment"] / employment_pc["Population"]
employment_pc = employment_pc.drop('Population', axis=1)

In [6]:
employment_pc.head(20)

      State  Year  Employment
0   Alabama  2008    0.547369
1   Alabama  2009    0.521131
2   Alabama  2010    0.513838
3   Alabama  2011    0.519051
4   Alabama  2012    0.517290
5   Alabama  2013    0.518579
6   Alabama  2014    0.522173
7   Alabama  2015    0.527103
8   Alabama  2016    0.531222
9   Alabama  2017    0.534862
10  Alabama  2018    0.540964
11  Alabama  2019    0.541993
12  Alabama  2020    0.530697
13  Alabama  2021    0.548334
14  Alabama  2022    0.562778
15  Alabama  2023    0.572782
16  Alabama  2024    0.575094
17   Alaska  2008    0.645282
18   Alaska  2009    0.633149
19   Alaska  2010    0.621752

In [7]:
employment_pc = employment_pc[employment_pc["Year"] >= 2008]

In [8]:
employment_pc.tail(20)

         State  Year  Employment
847  Wisconsin  2022    0.638142
848  Wisconsin  2023    0.647826
849  Wisconsin  2024    0.649292
850    Wyoming  2008    0.730692
851    Wyoming  2009    0.692131
852    Wyoming  2010    0.682271
853    Wyoming  2011    0.688620
854    Wyoming  2012    0.689366
855    Wyoming  2013    0.689421
856    Wyoming  2014    0.699535
857    Wyoming  2015    0.695674
858    Wyoming  2016    0.684088
859    Wyoming  2017    0.692364
860    Wyoming  2018    0.703902
861    Wyoming  2019    0.708936
862    Wyoming  2020    0.694929
863    Wyoming  2021    0.724210
864    Wyoming  2022    0.740823
865    Wyoming  2023    0.769020
866    Wyoming  2024    0.762295

In [9]:
employment_pc = employment_pc.reset_index(drop=True)

In [10]:
employment_pc.rename(columns={'Employment': 'employment_pc'}, inplace=True)

In [11]:
employment_pc.head(20)

      State  Year  employment_pc
0   Alabama  2008       0.547369
1   Alabama  2009       0.521131
2   Alabama  2010       0.513838
3   Alabama  2011       0.519051
4   Alabama  2012       0.517290
5   Alabama  2013       0.518579
6   Alabama  2014       0.522173
7   Alabama  2015       0.527103
8   Alabama  2016       0.531222
9   Alabama  2017       0.534862
10  Alabama  2018       0.540964
11  Alabama  2019       0.541993
12  Alabama  2020       0.530697
13  Alabama  2021       0.548334
14  Alabama  2022       0.562778
15  Alabama  2023       0.572782
16  Alabama  2024       0.575094
17   Alaska  2008       0.645282
18   Alaska  2009       0.633149
19   Alaska  2010       0.621752

In [12]:
print(f"Missing values:\n{employment_pc.isnull().sum()}")
print(f"\nTotal rows: {len(employment_pc)}")

Missing values:
State            0
Year             0
employment_pc    0
dtype: int64

Total rows: 867

In [13]:
employment_pc.to_csv("../data/cleaned/employment_pc_clean.csv", index=False)