In [37]:
import pandas as pd
import numpy as np

In [38]:
raw_gdp = pd.read_csv("../data/cleaned/gdp_clean.csv")
gdp_pc = raw_gdp.copy()

raw_population = pd.read_csv("../data/cleaned/population_cleaned.csv")
population = raw_population.copy()

In [39]:
gdp_pc = gdp_pc.merge(population[['State', 'Year', 'Population']], on=['State', 'Year'], how='left')
gdp_pc["GDP"] = gdp_pc["GDP"] * 1000000 / gdp_pc["Population"]
gdp_pc = gdp_pc.drop('Population', axis=1)

In [40]:
gdp_pc.head()

     State  Year  GDP
0  Alabama  1997  NaN
1  Alabama  1998  NaN
2  Alabama  1999  NaN
3  Alabama  2000  NaN
4  Alabama  2001  NaN

In [41]:
gdp_pc.info()

<class 'pandas.DataFrame'>
RangeIndex: 1428 entries, 0 to 1427
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   State   1428 non-null   str
 1   Year    1428 non-null   int64
 2   GDP     867 non-null    float64
dtypes: float64(1), int64(1), str(1)
memory usage: 33.6 KB

In [42]:
gdp_pc = gdp_pc[gdp_pc["Year"] >= 2008]

In [43]:
gdp_pc.head()

      State  Year           GDP
11  Alabama  2008  37019.494274
12  Alabama  2009  35913.982065
13  Alabama  2010  37073.345454
14  Alabama  2011  38003.908925
15  Alabama  2012  38901.397061

In [44]:
gdp_pc['GDP'] = gdp_pc['GDP'].round(2)

In [45]:
gdp_pc.head()

      State  Year       GDP
11  Alabama  2008  37019.49
12  Alabama  2009  35913.98
13  Alabama  2010  37073.35
14  Alabama  2011  38003.91
15  Alabama  2012  38901.40

In [46]:
gdp_pc = gdp_pc.reset_index(drop=True)

In [47]:
gdp_pc.head()

     State  Year       GDP
0  Alabama  2008  37019.49
1  Alabama  2009  35913.98
2  Alabama  2010  37073.35
3  Alabama  2011  38003.91
4  Alabama  2012  38901.40

In [48]:
gdp_pc.rename(columns={'GDP': 'gdp_pc'}, inplace=True)

In [49]:
gdp_pc.head()

     State  Year    gdp_pc
0  Alabama  2008  37019.49
1  Alabama  2009  35913.98
2  Alabama  2010  37073.35
3  Alabama  2011  38003.91
4  Alabama  2012  38901.40

In [50]:
print(f"Missing values:\n{gdp_pc.isnull().sum()}")
print(f"\nTotal rows: {len(gdp_pc)}")
print(f"\nGDP per capita range: ${gdp_pc['gdp_pc'].min():,.0f} to ${gdp_pc['gdp_pc'].max():,.0f}")

Missing values:
State     0
Year      0
gdp_pc    0
dtype: int64

Total rows: 867

GDP per capita range: $31,222 to $266,592

In [51]:
gdp_pc.to_csv("../data/cleaned/gdp_pc_clean.csv", index=False)