In [5]:
import pandas as pd
import numpy as np

In [6]:
incomepc_raw = pd.read_csv("../data/raw/income_per_capita.csv")

In [7]:
incomepc = incomepc_raw.copy()

In [8]:
incomepc.head()

,GeoFIPS,GeoName,1929,1930,1931,1932,1933,1934,1935,1936,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,00000,United States,699,621,528,402,375,427,477,539,...,48062.0,48974.0,51006.0,53311.0,55567.0,59151.0,64692.0,66298.0,70002.0,73204.0
1,01000,Alabama,319,263,220,159,164,207,216,249,...,38189.0,38704.0,39968.0,41324.0,42998.0,45872.0,50638.0,51697.0,54612.0,57311.0
2,02000,Alaska *,(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),...,56714.0,55536.0,56500.0,58997.0,60504.0,61903.0,65803.0,69160.0,72398.0,76234.0
3,04000,Arizona,598,518,430,322,309,362,416,462,...,39888.0,41173.0,43255.0,45297.0,47718.0,52077.0,57175.0,59060.0,63032.0,65798.0
4,05000,Arkansas,303,224,207,152,153,182,204,243,...,39267.0,40181.0,41403.0,43031.0,43737.0,47129.0,53353.0,53709.0,56547.0,59320.0

In [9]:
incomepc = incomepc.drop(columns=["GeoFIPS"])

In [10]:
incomepc.head()

,GeoName,1929,1930,1931,1932,1933,1934,1935,1936,1937,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,United States,699,621,528,402,375,427,477,539,579,...,48062.0,48974.0,51006.0,53311.0,55567.0,59151.0,64692.0,66298.0,70002.0,73204.0
1,Alabama,319,263,220,159,164,207,216,249,266,...,38189.0,38704.0,39968.0,41324.0,42998.0,45872.0,50638.0,51697.0,54612.0,57311.0
2,Alaska *,(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),(NA),...,56714.0,55536.0,56500.0,58997.0,60504.0,61903.0,65803.0,69160.0,72398.0,76234.0
3,Arizona,598,518,430,322,309,362,416,462,506,...,39888.0,41173.0,43255.0,45297.0,47718.0,52077.0,57175.0,59060.0,63032.0,65798.0
4,Arkansas,303,224,207,152,153,182,204,243,253,...,39267.0,40181.0,41403.0,43031.0,43737.0,47129.0,53353.0,53709.0,56547.0,59320.0

In [11]:
for i in range(1929, 1997):
    incomepc = incomepc.drop(columns=[str(i)])

In [12]:
incomepc.head()

,GeoName,1997,1998,1999,2000,2001,2002,2003,2004,2005,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,United States,25925.0,27493.0,28592.0,30551.0,31548.0,31801.0,32659.0,34183.0,35669.0,...,48062.0,48974.0,51006.0,53311.0,55567.0,59151.0,64692.0,66298.0,70002.0,73204.0
1,Alabama,21487.0,22651.0,23296.0,24258.0,25046.0,25671.0,26700.0,28385.0,29780.0,...,38189.0,38704.0,39968.0,41324.0,42998.0,45872.0,50638.0,51697.0,54612.0,57311.0
2,Alaska *,28219.0,29287.0,29941.0,31996.0,33591.0,34766.0,36045.0,37054.0,39013.0,...,56714.0,55536.0,56500.0,58997.0,60504.0,61903.0,65803.0,69160.0,72398.0,76234.0
3,Arizona,22757.0,24130.0,24866.0,26271.0,26946.0,27325.0,28384.0,30154.0,32150.0,...,39888.0,41173.0,43255.0,45297.0,47718.0,52077.0,57175.0,59060.0,63032.0,65798.0
4,Arkansas,20176.0,21203.0,21842.0,22731.0,23841.0,24280.0,25564.0,27024.0,28043.0,...,39267.0,40181.0,41403.0,43031.0,43737.0,47129.0,53353.0,53709.0,56547.0,59320.0

In [13]:
incomepc = incomepc[incomepc["GeoName"] != "United States"]

In [14]:
incomepc = incomepc.rename(columns={"GeoName": "State"})

In [15]:
incomepc.info()

<class 'pandas.DataFrame'>
RangeIndex: 65 entries, 1 to 65
Data columns (total 29 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   State   59 non-null     str
 1   1997    59 non-null     float64
 2   1998    59 non-null     float64
 3   1999    59 non-null     float64
 4   2000    59 non-null     float64
 5   2001    59 non-null     float64
 6   2002    59 non-null     float64
 7   2003    59 non-null     float64
 8   2004    59 non-null     float64
 9   2005    59 non-null     float64
 10  2006    59 non-null     float64
 11  2007    59 non-null     float64
 12  2008    59 non-null     float64
 13  2009    59 non-null     float64
 14  2010    59 non-null     float64
 15  2011    59 non-null     float64
 16  2012    59 non-null     float64
 17  2013    59 non-null     float64
 18  2014    59 non-null     float64
 19  2015    59 non-null     float64
 20  2016    59 non-null     float64
 21  2017    59 non-null     float64
 22  2018    59 non-null     float64
 23  2019    59 non-null     float64
 24  2020    59 non-null     float64
 25  2021    59 non-null     float64
 26  2022    59 non-null     float64
 27  2023    59 non-null     float64
 28  2024    59 non-null     float64
dtypes: float64(28), str(1)
memory usage: 14.9 KB

In [16]:
incomepc = incomepc.melt(id_vars="State", var_name="Year", value_name="Income_pc")

In [17]:
incomepc.head()

        State  Year  Income_pc
0     Alabama  1997    21487.0
1    Alaska *  1997    28219.0
2     Arizona  1997    22757.0
3    Arkansas  1997    20176.0
4  California  1997    26979.0

In [18]:
incomepc = incomepc.sort_values(by=["State", "Year"])

In [19]:
incomepc.head()

       State  Year  Income_pc
0    Alabama  1997    21487.0
65   Alabama  1998    22651.0
130  Alabama  1999    23296.0
195  Alabama  2000    24258.0
260  Alabama  2001    25046.0

In [20]:
incomepc = incomepc.reset_index(drop=True)

In [21]:
incomepc.tail()

     State  Year  Income_pc
1815   NaN  2024        NaN
1816   NaN  2024        NaN
1817   NaN  2024        NaN
1818   NaN  2024        NaN
1819   NaN  2024        NaN

In [22]:
incomepc = incomepc.dropna()

In [23]:
incomepc.tail()

        State  Year  Income_pc
1647  Wyoming  2020    65093.0
1648  Wyoming  2021    71459.0
1649  Wyoming  2022    77768.0
1650  Wyoming  2023    83038.0
1651  Wyoming  2024    86477.0

In [24]:
incomepc.isna().sum()

State        0
Year         0
Income_pc    0
dtype: int64

In [26]:
incomepc["State"].unique()

<StringArray>
[             'Alabama',             'Alaska *',              'Arizona',
             'Arkansas',           'California',             'Colorado',
          'Connecticut',             'Delaware', 'District of Columbia',
           'Far West *',              'Florida',              'Georgia',
          'Great Lakes',             'Hawaii *',                'Idaho',
             'Illinois',              'Indiana',                 'Iowa',
               'Kansas',             'Kentucky',            'Louisiana',
                'Maine',             'Maryland',        'Massachusetts',
             'Michigan',              'Mideast',            'Minnesota',
          'Mississippi',             'Missouri',              'Montana',
             'Nebraska',               'Nevada',          'New England',
        'New Hampshire',           'New Jersey',           'New Mexico',
             'New York',       'North Carolina',         'North Dakota',
                 'Ohio',             'Oklahoma',               'Oregon',
         'Pennsylvania',               'Plains',         'Rhode Island',
       'Rocky Mountain',       'South Carolina',         'South Dakota',
            'Southeast',            'Southwest',            'Tennessee',
                'Texas',                 'Utah',              'Vermont',
             'Virginia',           'Washington',        'West Virginia',
            'Wisconsin',              'Wyoming']
Length: 59, dtype: str

In [29]:
regions = [
    "Far West *", "Great Lakes", "Mideast", "New England",
    "Plains", "Rocky Mountain", "Southeast", "Southwest"
]

incomepc = incomepc[~incomepc["State"].isin(regions)]

In [30]:
incomepc["State"].unique()

<StringArray>
[             'Alabama',             'Alaska *',              'Arizona',
             'Arkansas',           'California',             'Colorado',
          'Connecticut',             'Delaware', 'District of Columbia',
              'Florida',              'Georgia',             'Hawaii *',
                'Idaho',             'Illinois',              'Indiana',
                 'Iowa',               'Kansas',             'Kentucky',
            'Louisiana',                'Maine',             'Maryland',
        'Massachusetts',             'Michigan',            'Minnesota',
          'Mississippi',             'Missouri',              'Montana',
             'Nebraska',               'Nevada',        'New Hampshire',
           'New Jersey',           'New Mexico',             'New York',
       'North Carolina',         'North Dakota',                 'Ohio',
             'Oklahoma',               'Oregon',         'Pennsylvania',
         'Rhode Island',       'South Carolina',         'South Dakota',
            'Tennessee',                'Texas',                 'Utah',
              'Vermont',             'Virginia',           'Washington',
        'West Virginia',            'Wisconsin',              'Wyoming']
Length: 51, dtype: str

In [44]:
incomepc["State"] = incomepc["State"].str.replace(" *", "", regex=False)

In [45]:
incomepc["State"].unique()

<StringArray>
[             'Alabama',               'Alaska',              'Arizona',
             'Arkansas',           'California',             'Colorado',
          'Connecticut',             'Delaware', 'District of Columbia',
              'Florida',              'Georgia',               'Hawaii',
                'Idaho',             'Illinois',              'Indiana',
                 'Iowa',               'Kansas',             'Kentucky',
            'Louisiana',                'Maine',             'Maryland',
        'Massachusetts',             'Michigan',            'Minnesota',
          'Mississippi',             'Missouri',              'Montana',
             'Nebraska',               'Nevada',        'New Hampshire',
           'New Jersey',           'New Mexico',             'New York',
       'North Carolina',         'North Dakota',                 'Ohio',
             'Oklahoma',               'Oregon',         'Pennsylvania',
         'Rhode Island',       'South Carolina',         'South Dakota',
            'Tennessee',                'Texas',                 'Utah',
              'Vermont',             'Virginia',           'Washington',
        'West Virginia',            'Wisconsin',              'Wyoming']
Length: 51, dtype: str

In [34]:
incomepc.head(20)

      State  Year  Income_pc
0   Alabama  1997    21487.0
1   Alabama  1998    22651.0
2   Alabama  1999    23296.0
3   Alabama  2000    24258.0
4   Alabama  2001    25046.0
5   Alabama  2002    25671.0
6   Alabama  2003    26700.0
7   Alabama  2004    28385.0
8   Alabama  2005    29780.0
9   Alabama  2006    31264.0
10  Alabama  2007    32516.0
11  Alabama  2008    33441.0
12  Alabama  2009    32717.0
13  Alabama  2010    33848.0
14  Alabama  2011    34884.0
15  Alabama  2012    35559.0
16  Alabama  2013    35706.0
17  Alabama  2014    36722.0
18  Alabama  2015    38189.0
19  Alabama  2016    38704.0

In [35]:
incomepc.info()

<class 'pandas.DataFrame'>
Index: 1428 entries, 0 to 1651
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   State      1428 non-null   str
 1   Year       1428 non-null   str
 2   Income_pc  1428 non-null   float64
dtypes: float64(1), str(2)
memory usage: 44.6 KB

In [36]:
incomepc["Year"] = incomepc["Year"].astype(int)

In [37]:
incomepc.info()

<class 'pandas.DataFrame'>
Index: 1428 entries, 0 to 1651
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   State      1428 non-null   str
 1   Year       1428 non-null   int64
 2   Income_pc  1428 non-null   float64
dtypes: float64(1), int64(1), str(1)
memory usage: 44.6 KB

In [38]:
incomepc = incomepc.reset_index(drop=True)

In [39]:
incomepc.info()

<class 'pandas.DataFrame'>
RangeIndex: 1428 entries, 0 to 1427
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   State      1428 non-null   str
 1   Year       1428 non-null   int64
 2   Income_pc  1428 non-null   float64
dtypes: float64(1), int64(1), str(1)
memory usage: 33.6 KB

In [40]:
incomepc["State"].value_counts()

State
Alabama                 28
Alaska *                28
Arizona                 28
Arkansas                28
California              28
Colorado                28
Connecticut             28
Delaware                28
District of Columbia    28
Florida                 28
Georgia                 28
Hawaii *                28
Idaho                   28
Illinois                28
Indiana                 28
Iowa                    28
Kansas                  28
Kentucky                28
Louisiana               28
Maine                   28
Maryland                28
Massachusetts           28
Michigan                28
Minnesota               28
Mississippi             28
Missouri                28
Montana                 28
Nebraska                28
Nevada                  28
New Hampshire           28
New Jersey              28
New Mexico              28
New York                28
North Carolina          28
North Dakota            28
Ohio                    28
Oklahoma                28
Oregon                  28
Pennsylvania            28
Rhode Island            28
South Carolina          28
South Dakota            28
Tennessee               28
Texas                   28
Utah                    28
Vermont                 28
Virginia                28
Washington              28
West Virginia           28
Wisconsin               28
Wyoming                 28
Name: count, dtype: int64

In [47]:
incomepc.to_csv("../data/cleaned/incomepc_clean.csv", index=False)