In [7]:
import pandas as pd
import numpy as np

In [8]:
df_gdp = pd.read_csv("../data/cleaned/gdp_clean.csv")
df_income = pd.read_csv("../data/cleaned/income_pc_clean.csv")
df_real_income = pd.read_csv("../data/cleaned/real_income_pc_clean.csv")
df_rpp = pd.read_csv("../data/cleaned/regional_price_parity_clean.csv")
df_employment = pd.read_csv("../data/cleaned/employment_clean.csv")
df_population = pd.read_csv("../data/cleaned/population_cleaned.csv")

In [9]:
df_gdp["Year"].unique()

array([1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007,
       2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018,
       2019, 2020, 2021, 2022, 2023, 2024])

In [10]:
for i in range(1997,2008):
    df_gdp = df_gdp[df_gdp["Year"]!= i]

In [11]:
df_gdp["Year"].unique()

array([2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018,
       2019, 2020, 2021, 2022, 2023, 2024])

In [12]:
df_income["Year"].unique()

array([1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007,
       2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018,
       2019, 2020, 2021, 2022, 2023, 2024])

In [13]:
df_real_income["Year"].unique()

array([2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018,
       2019, 2020, 2021, 2022, 2023, 2024])

In [14]:
df_rpp["Year"].unique()

array([2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018,
       2019, 2020, 2021, 2022, 2023, 2024])

In [15]:
df_employment["Year"].unique()

array([2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018,
       2019, 2020, 2021, 2022, 2023, 2024])

In [16]:
df_population["Year"].unique()

array([2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018,
       2019, 2020, 2021, 2022, 2023, 2024])

In [17]:
df = df_gdp.merge(df_income, on=["State", "Year"], how="outer")
df = df.merge(df_real_income, on=["State", "Year"], how="outer")
df = df.merge(df_rpp, on=["State", "Year"], how="outer")
df = df.merge(df_employment, on=["State", "Year"], how="outer")
df = df.merge(df_population, on=["State", "Year"], how="outer")

In [18]:
df.head()

     State  Year  GDP  Income_pc  Real_Income_pc  RPP  Employment  Population
0  Alabama  1997  NaN    21487.0             NaN  NaN         NaN         NaN
1  Alabama  1998  NaN    22651.0             NaN  NaN         NaN         NaN
2  Alabama  1999  NaN    23296.0             NaN  NaN         NaN         NaN
3  Alabama  2000  NaN    24258.0             NaN  NaN         NaN         NaN
4  Alabama  2001  NaN    25046.0             NaN  NaN         NaN         NaN

In [19]:
for i in range(1997,2008):
    df = df[df["Year"]!= i]

In [20]:
df.head()

,State,Year,GDP,Income_pc,Real_Income_pc,RPP,Employment,Population
11,Alabama,2008,1.746656e+11,33441.0,42219.0,88.901,2582600.0,4718206.0
12,Alabama,2009,1.708765e+11,32717.0,41966.0,87.786,2479511.0,4757938.0
13,Alabama,2010,1.775107e+11,33848.0,41709.0,89.783,2460305.0,4788095.0
14,Alabama,2011,1.828967e+11,34884.0,41819.0,90.011,2497974.0,4812576.0
15,Alabama,2012,1.882807e+11,35559.0,41592.0,90.559,2503656.0,4839947.0

In [21]:
df.tail()

,State,Year,GDP,Income_pc,Real_Income_pc,RPP,Employment,Population
1423,Wyoming,2020,3.698270e+10,65093.0,67906.0,91.836,401439.0,577669.0
1424,Wyoming,2021,4.241060e+10,71459.0,71860.0,91.440,419797.0,579662.0
1425,Wyoming,2022,4.957040e+10,77768.0,73081.0,91.767,430968.0,581742.0
1426,Wyoming,2023,5.135010e+10,83038.0,75323.0,91.551,449620.0,584666.0
1427,Wyoming,2024,5.149810e+10,86477.0,75501.0,92.691,447255.0,586722.0

In [22]:
df.head(50)

,State,Year,GDP,Income_pc,Real_Income_pc,RPP,Employment,Population
11,Alabama,2008,1.746656e+11,33441.0,42219.0,88.901,2582600.0,4718206.0
12,Alabama,2009,1.708765e+11,32717.0,41966.0,87.786,2479511.0,4757938.0
13,Alabama,2010,1.775107e+11,33848.0,41709.0,89.783,2460305.0,4788095.0
14,Alabama,2011,1.828967e+11,34884.0,41819.0,90.011,2497974.0,4812576.0
15,Alabama,2012,1.882807e+11,35559.0,41592.0,90.559,2503656.0,4839947.0
16,Alabama,2013,1.939815e+11,35706.0,41325.0,90.324,2523020.0,4865253.0
17,Alabama,2014,1.970644e+11,36722.0,41984.0,90.175,2552256.0,4887757.0
18,Alabama,2015,2.031133e+11,38189.0,43809.0,89.741,2587641.0,4909177.0
19,Alabama,2016,2.088243e+11,38704.0,43554.0,90.609,2619761.0,4931579.0
20,Alabama,2017,2.166155e+11,39968.0,44481.0,90.065,2649222.0,4953096.0
21,Alabama,2018,2.262638e+11,41324.0,46440.0,87.378,2692424.0,4977088.0
22,Alabama,2019,2.347982e+11,42998.0,47130.0,88.303,2712014.0,5003778.0
23,Alabama,2020,2.358590e+11,45872.0,50186.0,87.569,2670980.0,5032962.0
24,Alabama,2021,2.603250e+11,50638.0,52875.0,88.062,2769117.0,5050058.0
25,Alabama,2022,2.868733e+11,51697.0,50649.0,88.021,2857149.0,5076868.0
26,Alabama,2023,3.095438e+11,54612.0,50902.0,89.097,2931413.0,5117850.0
27,Alabama,2024,3.253451e+11,57311.0,52216.0,88.823,2969241.0,5163055.0
39,Alaska,2008,5.524670e+10,47800.0,51647.0,103.878,443602.0,687455.0
40,Alaska,2009,5.016590e+10,47211.0,50081.0,106.147,442505.0,698895.0
41,Alaska,2010,5.365400e+10,49543.0,53163.0,103.099,443940.0,714015.0
42,Alaska,2011,5.691230e+10,52415.0,54766.0,103.274,450420.0,722513.0
43,Alaska,2012,5.832070e+10,53340.0,55096.0,102.548,459282.0,731106.0
44,Alaska,2013,5.753300e+10,52252.0,53525.0,102.052,461205.0,738054.0
45,Alaska,2014,5.658740e+10,55098.0,55480.0,102.386,461371.0,737634.0
46,Alaska,2015,5.157420e+10,56714.0,56528.0,103.287,461707.0,739120.0
47,Alaska,2016,5.112180e+10,55536.0,54411.0,104.073,457142.0,743397.0
48,Alaska,2017,5.355090e+10,56500.0,54022.0,104.833,455550.0,741937.0
49,Alaska,2018,5.476200e+10,58997.0,55403.0,104.565,454776.0,737710.0
50,Alaska,2019,5.454960e+10,60504.0,56834.0,103.041,454794.0,734820.0
51,Alaska,2020,5.186170e+10,61903.0,58522.0,101.339,430889.0,732906.0
52,Alaska,2021,5.936300e+10,65803.0,57677.0,104.907,443016.0,734590.0
53,Alaska,2022,6.568250e+10,69160.0,58413.0,102.101,454025.0,733659.0
54,Alaska,2023,6.823270e+10,72398.0,58204.0,103.297,467104.0,734654.0
55,Alaska,2024,7.156720e+10,76234.0,60272.0,102.359,474188.0,736537.0
67,Arizona,2008,2.610058e+11,35586.0,38966.0,102.504,3402806.0,6280362.0
68,Arizona,2009,2.448622e+11,33467.0,36634.0,102.865,3228516.0,6343154.0
69,Arizona,2010,2.505270e+11,33778.0,37162.0,100.558,3181563.0,6401304.0
70,Arizona,2011,2.616914e+11,35263.0,38403.0,99.083,3239037.0,6443158.0
71,Arizona,2012,2.727033e+11,36364.0,39284.0,98.050,3295532.0,6501800.0
72,Arizona,2013,2.786795e+11,36918.0,39204.0,98.441,3371101.0,6555926.0
73,Arizona,2014,2.866760e+11,38268.0,40281.0,97.944,3448146.0,6629890.0
74,Arizona,2015,2.989422e+11,39888.0,41960.0,97.865,3547647.0,6705607.0
75,Arizona,2016,3.137871e+11,41173.0,42568.0,98.622,3644791.0,6793278.0
76,Arizona,2017,3.330990e+11,43255.0,44279.0,97.915,3740747.0,6872380.0
77,Arizona,2018,3.536710e+11,45297.0,45675.0,97.381,3854741.0,6964300.0
78,Arizona,2019,3.753767e+11,47718.0,47236.0,97.779,3929587.0,7067695.0
79,Arizona,2020,3.905032e+11,52077.0,50292.0,99.203,3919887.0,7186647.0
80,Arizona,2021,4.381360e+11,57175.0,54424.0,96.600,4085773.0,7274022.0
81,Arizona,2022,4.887222e+11,59060.0,50935.0,99.992,4250495.0,7370065.0
82,Arizona,2023,5.301050e+11,63032.0,51960.0,100.742,4404247.0,7452073.0

In [23]:
df = df.reset_index(drop=True)

In [24]:
df.head()

,State,Year,GDP,Income_pc,Real_Income_pc,RPP,Employment,Population
0,Alabama,2008,1.746656e+11,33441.0,42219.0,88.901,2582600.0,4718206.0
1,Alabama,2009,1.708765e+11,32717.0,41966.0,87.786,2479511.0,4757938.0
2,Alabama,2010,1.775107e+11,33848.0,41709.0,89.783,2460305.0,4788095.0
3,Alabama,2011,1.828967e+11,34884.0,41819.0,90.011,2497974.0,4812576.0
4,Alabama,2012,1.882807e+11,35559.0,41592.0,90.559,2503656.0,4839947.0

In [25]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 867 entries, 0 to 866
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   State           867 non-null    str
 1   Year            867 non-null    int64
 2   GDP             867 non-null    float64
 3   Income_pc       867 non-null    float64
 4   Real_Income_pc  867 non-null    float64
 5   RPP             867 non-null    float64
 6   Employment      867 non-null    float64
 7   Population      867 non-null    float64
dtypes: float64(6), int64(1), str(1)
memory usage: 54.3 KB

In [26]:
df["State"].nunique(), df["Year"].nunique()

(51, 17)

In [27]:
df.shape

(867, 8)

In [28]:
df.groupby("State")["Year"].count()

State
Alabama                 17
Alaska                  17
Arizona                 17
Arkansas                17
California              17
Colorado                17
Connecticut             17
Delaware                17
District of Columbia    17
Florida                 17
Georgia                 17
Hawaii                  17
Idaho                   17
Illinois                17
Indiana                 17
Iowa                    17
Kansas                  17
Kentucky                17
Louisiana               17
Maine                   17
Maryland                17
Massachusetts           17
Michigan                17
Minnesota               17
Mississippi             17
Missouri                17
Montana                 17
Nebraska                17
Nevada                  17
New Hampshire           17
New Jersey              17
New Mexico              17
New York                17
North Carolina          17
North Dakota            17
Ohio                    17
Oklahoma                17
Oregon                  17
Pennsylvania            17
Rhode Island            17
South Carolina          17
South Dakota            17
Tennessee               17
Texas                   17
Utah                    17
Vermont                 17
Virginia                17
Washington              17
West Virginia           17
Wisconsin               17
Wyoming                 17
Name: Year, dtype: int64

In [29]:
df.duplicated(subset=["State", "Year"]).sum()

np.int64(0)

In [30]:
pd.options.display.float_format = '{:,.0f}'.format

In [31]:
df.describe()

,Year,GDP,Income_pc,Real_Income_pc,RPP,Employment,Population
count,867,867,867,867,867,867,867
mean,"2,016","387,285,547,520","51,314","51,366",98,"3,776,736","6,330,303"
std,5,"506,742,054,255","13,075","7,771",7,"4,234,333","7,130,425"
min,"2,008","26,140,400,000","30,220","35,790",85,"385,075","546,043"
25%,"2,012","94,266,050,000","41,158","45,706",92,"916,786","1,772,020"
50%,"2,016","234,022,200,000","48,578","50,686",97,"2,493,913","4,443,778"
75%,"2,020","466,580,600,000","59,220","56,142",102,"4,628,468","7,262,656"
max,"2,024","4,048,108,100,000","111,185","81,872",114,"25,583,169","39,547,995"

In [32]:
df.columns = df.columns.str.lower()

In [33]:
print(df.columns)

Index(['state', 'year', 'gdp', 'income_pc', 'real_income_pc', 'rpp',
       'employment', 'population'],
      dtype='str')

In [34]:
df.head()

,state,year,gdp,income_pc,real_income_pc,rpp,employment,population
0,Alabama,2008,"174,665,600,000","33,441","42,219",89,"2,582,600","4,718,206"
1,Alabama,2009,"170,876,500,000","32,717","41,966",88,"2,479,511","4,757,938"
2,Alabama,2010,"177,510,700,000","33,848","41,709",90,"2,460,305","4,788,095"
3,Alabama,2011,"182,896,700,000","34,884","41,819",90,"2,497,974","4,812,576"
4,Alabama,2012,"188,280,700,000","35,559","41,592",91,"2,503,656","4,839,947"

In [35]:
pd.options.display.float_format = '{:,.2f}'.format

In [36]:
df.describe()

,year,gdp,income_pc,real_income_pc,rpp,employment,population
count,867.00,867.00,867.00,867.00,867.00,867.00,867.00
mean,"2,016.00","387,285,547,520.18","51,314.05","51,366.15",97.50,"3,776,735.99","6,330,302.68"
std,4.90,"506,742,054,254.98","13,075.49","7,770.85",6.94,"4,234,332.96","7,130,425.19"
min,"2,008.00","26,140,400,000.00","30,220.00","35,790.00",85.02,"385,075.00","546,043.00"
25%,"2,012.00","94,266,050,000.00","41,158.50","45,706.50",91.84,"916,786.00","1,772,019.50"
50%,"2,016.00","234,022,200,000.00","48,578.00","50,686.00",96.72,"2,493,913.00","4,443,778.00"
75%,"2,020.00","466,580,600,000.00","59,219.50","56,142.00",102.41,"4,628,468.00","7,262,656.50"
max,"2,024.00","4,048,108,100,000.00","111,185.00","81,872.00",114.24,"25,583,169.00","39,547,995.00"

In [37]:
df.to_csv("../data/processed/master_dataset_v1.csv", index=False)

In [38]:
# Load additional datasets to add to master_v1
df_gdp_pc = pd.read_csv("../data/cleaned/gdp_pc_clean.csv")
df_employment_pc = pd.read_csv("../data/cleaned/employment_pc_clean.csv")

master = pd.read_csv("../data/processed/master_dataset_v1.csv")

df_gdp_pc.columns = ['state', 'year', 'gdp_pc']
df_employment_pc.columns = ['state', 'year', 'employment_pc']

master = master.merge(df_gdp_pc, on=['state', 'year'], how='left')
master = master.merge(df_employment_pc, on=['state', 'year'], how='left')

master.to_csv("../data/processed/master_dataset_v1.csv", index=False)

print(f"Master dataset shape: {master.shape}")
print(f"\nColumns: {list(master.columns)}")

Master dataset shape: (867, 10)

Columns: ['state', 'year', 'gdp', 'income_pc', 'real_income_pc', 'rpp', 'employment', 'population', 'gdp_pc', 'employment_pc']

In [39]:
# Create organized master_dataset_v2
master_v2 = master.copy()

# 1. Geographic/Time identifiers
# 2. Population (base metric)
# 3. Economic output (GDP metrics)
# 4. Employment metrics
# 5. Income metrics
# 6. Cost of living adjustment

column_order = [
    'state', 'year', 'population',
    'gdp', 'gdp_pc',
    'employment', 'employment_pc',
    'income_pc', 'real_income_pc',
    'rpp'
]

master_v2 = master_v2[column_order]

# Check for any missing values
print("Missing values per column:")
print(master_v2.isnull().sum())
print("\n" + "="*60)
print(f"Dataset shape: {master_v2.shape}")
print(f"States: {master_v2['state'].nunique()}")
print(f"Year range: {master_v2['year'].min()}-{master_v2['year'].max()}")
print("="*60 + "\n")

# Display sample data
print("Sample data (first 5 rows):")
print(master_v2.head())
print("\nSample data (random state):")
print(master_v2[master_v2['state'] == 'California'].head())

Missing values per column:
state             0
year              0
population        0
gdp               0
gdp_pc            0
employment        0
employment_pc     0
income_pc         0
real_income_pc    0
rpp               0
dtype: int64

============================================================
Dataset shape: (867, 10)
States: 51
Year range: 2008-2024
============================================================

Sample data (first 5 rows):
     state  year   population                gdp    gdp_pc   employment  \
0  Alabama  2008 4,718,206.00 174,665,600,000.00 37,019.49 2,582,600.00
1  Alabama  2009 4,757,938.00 170,876,500,000.00 35,913.98 2,479,511.00
2  Alabama  2010 4,788,095.00 177,510,700,000.00 37,073.35 2,460,305.00
3  Alabama  2011 4,812,576.00 182,896,700,000.00 38,003.91 2,497,974.00
4  Alabama  2012 4,839,947.00 188,280,700,000.00 38,901.40 2,503,656.00

   employment_pc  income_pc  real_income_pc   rpp
0           0.55  33,441.00       42,219.00 88.90
1           0.52  32,717.00       41,966.00 87.79
2           0.51  33,848.00       41,709.00 89.78
3           0.52  34,884.00       41,819.00 90.01
4           0.52  35,559.00       41,592.00 90.56

Sample data (random state):
         state  year    population                  gdp    gdp_pc  \
68  California  2008 36,604,337.00 1,946,241,500,000.00 53,169.70
69  California  2009 36,961,229.00 1,879,809,500,000.00 50,858.96
70  California  2010 37,322,523.00 1,938,603,300,000.00 51,941.91
71  California  2011 37,651,212.00 2,014,050,300,000.00 53,492.31
72  California  2012 37,971,412.00 2,108,873,100,000.00 55,538.44

      employment  employment_pc  income_pc  real_income_pc    rpp
68 20,654,365.00           0.56  43,391.00       43,788.00 111.22
69 19,837,727.00           0.54  41,660.00       42,377.00 110.70
70 19,642,544.00           0.53  43,137.00       43,503.00 109.70
71 19,986,185.00           0.53  45,508.00       44,844.00 109.50
72 20,666,919.00           0.54  47,793.00       46,162.00 109.67

In [40]:
# Summary statistics by column
print("\nColumn Summary Statistics:")
print("="*60)
print(master_v2.describe().round(2))
print("\nData types:")
print(master_v2.dtypes)

Column Summary Statistics:
============================================================
          year    population                  gdp     gdp_pc    employment  \
count   867.00        867.00               867.00     867.00        867.00
mean  2,016.00  6,330,302.68   387,285,547,520.18  61,054.50  3,776,735.99
std       4.90  7,130,425.19   506,742,054,254.98  25,327.67  4,234,332.96
min   2,008.00    546,043.00    26,140,400,000.00  31,221.72    385,075.00
25%   2,012.00  1,772,019.50    94,266,050,000.00  46,916.58    916,786.00
50%   2,016.00  4,443,778.00   234,022,200,000.00  55,762.12  2,493,913.00
75%   2,020.00  7,262,656.50   466,580,600,000.00  68,296.69  4,628,468.00
max   2,024.00 39,547,995.00 4,048,108,100,000.00 266,591.98 25,583,169.00

       employment_pc  income_pc  real_income_pc    rpp
count         867.00     867.00          867.00 867.00
mean            0.62  51,314.05       51,366.15  97.50
std             0.11  13,075.49        7,770.85   6.94
min             0.47  30,220.00       35,790.00  85.02
25%             0.57  41,158.50       45,706.50  91.84
50%             0.60  48,578.00       50,686.00  96.72
75%             0.64  59,219.50       56,142.00 102.41
max             1.37 111,185.00       81,872.00 114.24

Data types:
state                 str
year                int64
population        float64
gdp               float64
gdp_pc            float64
employment        float64
employment_pc     float64
income_pc         float64
real_income_pc    float64
rpp               float64
dtype: object

In [41]:
master_v2.to_csv("../data/processed/master_dataset_v2.csv", index=False)

In [43]:
master_v2 = pd.read_csv("../data/processed/master_dataset_v2.csv")
master_v2['population'] = master_v2['population'].astype(int)

In [ ]:
master_v2.