In [42]:
import pandas as pd
import numpy as np

In [43]:
df_gdp = pd.read_csv("../data/cleaned/gdp_clean.csv")
df_income = pd.read_csv("../data/cleaned/income_pc_clean.csv")
df_real_income = pd.read_csv("../data/cleaned/real_income_pc_clean.csv")
df_rpp = pd.read_csv("../data/cleaned/regional_price_parity_clean.csv")
df_employment = pd.read_csv("../data/cleaned/employment_clean.csv")

In [44]:
df_gdp["Year"].unique()

array([1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007,
       2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018,
       2019, 2020, 2021, 2022, 2023, 2024])

In [45]:
for i in range(1997,2008):
    df_gdp = df_gdp[df_gdp["Year"]!= i]

In [46]:
df_gdp["Year"].unique()

array([2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018,
       2019, 2020, 2021, 2022, 2023, 2024])

In [47]:
df_income["Year"].unique()

array([1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007,
       2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018,
       2019, 2020, 2021, 2022, 2023, 2024])

In [48]:
df_real_income["Year"].unique()

array([2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018,
       2019, 2020, 2021, 2022, 2023, 2024])

In [49]:
df_rpp["Year"].unique()

array([2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018,
       2019, 2020, 2021, 2022, 2023, 2024])

In [50]:
df_employment["Year"].unique()

array([2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018,
       2019, 2020, 2021, 2022, 2023, 2024])

In [51]:
df = df_gdp.merge(df_income, on=["State", "Year"], how="outer")
df = df.merge(df_real_income, on=["State", "Year"], how="outer")
df = df.merge(df_rpp, on=["State", "Year"], how="outer")
df = df.merge(df_employment, on=["State", "Year"], how="outer")

In [52]:
df.head()

     State  Year  GDP  Income_pc  Real_Income_pc  RPP  Employment
0  Alabama  1997  NaN  21,487.00             NaN  NaN         NaN
1  Alabama  1998  NaN  22,651.00             NaN  NaN         NaN
2  Alabama  1999  NaN  23,296.00             NaN  NaN         NaN
3  Alabama  2000  NaN  24,258.00             NaN  NaN         NaN
4  Alabama  2001  NaN  25,046.00             NaN  NaN         NaN

In [53]:
for i in range(1997,2008):
    df = df[df["Year"]!= i]

In [54]:
df.head()

      State  Year        GDP  Income_pc  Real_Income_pc   RPP   Employment
11  Alabama  2008 174,665.60  33,441.00       42,219.00 88.90 2,582,600.00
12  Alabama  2009 170,876.50  32,717.00       41,966.00 87.79 2,479,511.00
13  Alabama  2010 177,510.70  33,848.00       41,709.00 89.78 2,460,305.00
14  Alabama  2011 182,896.70  34,884.00       41,819.00 90.01 2,497,974.00
15  Alabama  2012 188,280.70  35,559.00       41,592.00 90.56 2,503,656.00

In [55]:
df.tail()

        State  Year       GDP  Income_pc  Real_Income_pc   RPP  Employment
1423  Wyoming  2020 36,982.70  65,093.00       67,906.00 91.84  401,439.00
1424  Wyoming  2021 42,410.60  71,459.00       71,860.00 91.44  419,797.00
1425  Wyoming  2022 49,570.40  77,768.00       73,081.00 91.77  430,968.00
1426  Wyoming  2023 51,350.10  83,038.00       75,323.00 91.55  449,620.00
1427  Wyoming  2024 51,498.10  86,477.00       75,501.00 92.69  447,255.00

In [56]:
df.head(50)

      State  Year        GDP  Income_pc  Real_Income_pc    RPP   Employment
11  Alabama  2008 174,665.60  33,441.00       42,219.00  88.90 2,582,600.00
12  Alabama  2009 170,876.50  32,717.00       41,966.00  87.79 2,479,511.00
13  Alabama  2010 177,510.70  33,848.00       41,709.00  89.78 2,460,305.00
14  Alabama  2011 182,896.70  34,884.00       41,819.00  90.01 2,497,974.00
15  Alabama  2012 188,280.70  35,559.00       41,592.00  90.56 2,503,656.00
16  Alabama  2013 193,981.50  35,706.00       41,325.00  90.32 2,523,020.00
17  Alabama  2014 197,064.40  36,722.00       41,984.00  90.17 2,552,256.00
18  Alabama  2015 203,113.30  38,189.00       43,809.00  89.74 2,587,641.00
19  Alabama  2016 208,824.30  38,704.00       43,554.00  90.61 2,619,761.00
20  Alabama  2017 216,615.50  39,968.00       44,481.00  90.06 2,649,222.00
21  Alabama  2018 226,263.80  41,324.00       46,440.00  87.38 2,692,424.00
22  Alabama  2019 234,798.20  42,998.00       47,130.00  88.30 2,712,014.00
23  Alabama  2020 235,859.00  45,872.00       50,186.00  87.57 2,670,980.00
24  Alabama  2021 260,325.00  50,638.00       52,875.00  88.06 2,769,117.00
25  Alabama  2022 286,873.30  51,697.00       50,649.00  88.02 2,857,149.00
26  Alabama  2023 309,543.80  54,612.00       50,902.00  89.10 2,931,413.00
27  Alabama  2024 325,345.10  57,311.00       52,216.00  88.82 2,969,241.00
39   Alaska  2008  55,246.70  47,800.00       51,647.00 103.88   443,602.00
40   Alaska  2009  50,165.90  47,211.00       50,081.00 106.15   442,505.00
41   Alaska  2010  53,654.00  49,543.00       53,163.00 103.10   443,940.00
42   Alaska  2011  56,912.30  52,415.00       54,766.00 103.27   450,420.00
43   Alaska  2012  58,320.70  53,340.00       55,096.00 102.55   459,282.00
44   Alaska  2013  57,533.00  52,252.00       53,525.00 102.05   461,205.00
45   Alaska  2014  56,587.40  55,098.00       55,480.00 102.39   461,371.00
46   Alaska  2015  51,574.20  56,714.00       56,528.00 103.29   461,707.00
47   Alaska  2016  51,121.80  55,536.00       54,411.00 104.07   457,142.00
48   Alaska  2017  53,550.90  56,500.00       54,022.00 104.83   455,550.00
49   Alaska  2018  54,762.00  58,997.00       55,403.00 104.56   454,776.00
50   Alaska  2019  54,549.60  60,504.00       56,834.00 103.04   454,794.00
51   Alaska  2020  51,861.70  61,903.00       58,522.00 101.34   430,889.00
52   Alaska  2021  59,363.00  65,803.00       57,677.00 104.91   443,016.00
53   Alaska  2022  65,682.50  69,160.00       58,413.00 102.10   454,025.00
54   Alaska  2023  68,232.70  72,398.00       58,204.00 103.30   467,104.00
55   Alaska  2024  71,567.20  76,234.00       60,272.00 102.36   474,188.00
67  Arizona  2008 261,005.80  35,586.00       38,966.00 102.50 3,402,806.00
68  Arizona  2009 244,862.20  33,467.00       36,634.00 102.86 3,228,516.00
69  Arizona  2010 250,527.00  33,778.00       37,162.00 100.56 3,181,563.00
70  Arizona  2011 261,691.40  35,263.00       38,403.00  99.08 3,239,037.00
71  Arizona  2012 272,703.30  36,364.00       39,284.00  98.05 3,295,532.00
72  Arizona  2013 278,679.50  36,918.00       39,204.00  98.44 3,371,101.00
73  Arizona  2014 286,676.00  38,268.00       40,281.00  97.94 3,448,146.00
74  Arizona  2015 298,942.20  39,888.00       41,960.00  97.86 3,547,647.00
75  Arizona  2016 313,787.10  41,173.00       42,568.00  98.62 3,644,791.00
76  Arizona  2017 333,099.00  43,255.00       44,279.00  97.92 3,740,747.00
77  Arizona  2018 353,671.00  45,297.00       45,675.00  97.38 3,854,741.00
78  Arizona  2019 375,376.70  47,718.00       47,236.00  97.78 3,929,587.00
79  Arizona  2020 390,503.20  52,077.00       50,292.00  99.20 3,919,887.00
80  Arizona  2021 438,136.00  57,175.00       54,424.00  96.60 4,085,773.00
81  Arizona  2022 488,722.20  59,060.00       50,935.00  99.99 4,250,495.00
82  Arizona  2023 530,105.00  63,032.00       51,960.00 100.74 4,404,247.00

In [57]:
df = df.reset_index(drop=True)

In [58]:
df.head()

     State  Year        GDP  Income_pc  Real_Income_pc   RPP   Employment
0  Alabama  2008 174,665.60  33,441.00       42,219.00 88.90 2,582,600.00
1  Alabama  2009 170,876.50  32,717.00       41,966.00 87.79 2,479,511.00
2  Alabama  2010 177,510.70  33,848.00       41,709.00 89.78 2,460,305.00
3  Alabama  2011 182,896.70  34,884.00       41,819.00 90.01 2,497,974.00
4  Alabama  2012 188,280.70  35,559.00       41,592.00 90.56 2,503,656.00

In [59]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 867 entries, 0 to 866
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   State           867 non-null    str
 1   Year            867 non-null    int64
 2   GDP             867 non-null    float64
 3   Income_pc       867 non-null    float64
 4   Real_Income_pc  867 non-null    float64
 5   RPP             867 non-null    float64
 6   Employment      867 non-null    float64
dtypes: float64(5), int64(1), str(1)
memory usage: 47.5 KB

In [60]:
df["State"].nunique(), df["Year"].nunique()

(51, 17)

In [61]:
df.shape

(867, 7)

In [62]:
df.groupby("State")["Year"].count()

State
Alabama                 17
Alaska                  17
Arizona                 17
Arkansas                17
California              17
Colorado                17
Connecticut             17
Delaware                17
District of Columbia    17
Florida                 17
Georgia                 17
Hawaii                  17
Idaho                   17
Illinois                17
Indiana                 17
Iowa                    17
Kansas                  17
Kentucky                17
Louisiana               17
Maine                   17
Maryland                17
Massachusetts           17
Michigan                17
Minnesota               17
Mississippi             17
Missouri                17
Montana                 17
Nebraska                17
Nevada                  17
New Hampshire           17
New Jersey              17
New Mexico              17
New York                17
North Carolina          17
North Dakota            17
Ohio                    17
Oklahoma                17
Oregon                  17
Pennsylvania            17
Rhode Island            17
South Carolina          17
South Dakota            17
Tennessee               17
Texas                   17
Utah                    17
Vermont                 17
Virginia                17
Washington              17
West Virginia           17
Wisconsin               17
Wyoming                 17
Name: Year, dtype: int64

In [63]:
df.duplicated(subset=["State", "Year"]).sum()

np.int64(0)

In [64]:
pd.options.display.float_format = '{:,.0f}'.format

In [65]:
df.describe()

       Year       GDP  Income_pc  Real_Income_pc  RPP  Employment
count   867       867        867             867  867         867
mean  2,016   387,286     51,314          51,366   98   3,776,736
std       5   506,742     13,075           7,771    7   4,234,333
min   2,008    26,140     30,220          35,790   85     385,075
25%   2,012    94,266     41,158          45,706   92     916,786
50%   2,016   234,022     48,578          50,686   97   2,493,913
75%   2,020   466,581     59,220          56,142  102   4,628,468
max   2,024 4,048,108    111,185          81,872  114  25,583,169

In [66]:
df.columns = df.columns.str.lower()

In [67]:
print(df.columns)

Index(['state', 'year', 'gdp', 'income_pc', 'real_income_pc', 'rpp',
       'employment'],
      dtype='str')

In [68]:
df.head()

     state  year     gdp  income_pc  real_income_pc  rpp  employment
0  Alabama  2008 174,666     33,441          42,219   89   2,582,600
1  Alabama  2009 170,876     32,717          41,966   88   2,479,511
2  Alabama  2010 177,511     33,848          41,709   90   2,460,305
3  Alabama  2011 182,897     34,884          41,819   90   2,497,974
4  Alabama  2012 188,281     35,559          41,592   91   2,503,656

In [69]:
pd.options.display.float_format = '{:,.2f}'.format

In [70]:
df.describe()

          year          gdp  income_pc  real_income_pc    rpp    employment
count   867.00       867.00     867.00          867.00 867.00        867.00
mean  2,016.00   387,285.55  51,314.05       51,366.15  97.50  3,776,735.99
std       4.90   506,742.05  13,075.49        7,770.85   6.94  4,234,332.96
min   2,008.00    26,140.40  30,220.00       35,790.00  85.02    385,075.00
25%   2,012.00    94,266.05  41,158.50       45,706.50  91.84    916,786.00
50%   2,016.00   234,022.20  48,578.00       50,686.00  96.72  2,493,913.00
75%   2,020.00   466,580.60  59,219.50       56,142.00 102.41  4,628,468.00
max   2,024.00 4,048,108.10 111,185.00       81,872.00 114.24 25,583,169.00

In [71]:
df.to_csv("../data/processed/master_dataset_v1.csv", index=False)