In [2]:
import pandas as pd
import numpy as np

In [9]:
df_gdp = pd.read_csv("../data/cleaned/gdp_clean.csv")
df_income = pd.read_csv("../data/cleaned/income_pc_clean.csv")
df_real_income = pd.read_csv("../data/cleaned/real_income_pc_clean.csv")
df_rpp = pd.read_csv("../data/cleaned/regional_price_parity_clean.csv")

In [ ]:
df_gdp["Year"].unique()

array([1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007,
       2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018,
       2019, 2020, 2021, 2022, 2023, 2024])

In [ ]:
for i in range(1997,2008):
    df = df[df["Year"]!= i]

1997
1998
1999
2000
2001
2002
2003
2004
2005
2006
2007

In [20]:
df_income["Year"].unique()

array([1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007,
       2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018,
       2019, 2020, 2021, 2022, 2023, 2024])

In [21]:
df_real_income["Year"].unique()

array([2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018,
       2019, 2020, 2021, 2022, 2023, 2024])

In [22]:
df_rpp["Year"].unique()

array([2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018,
       2019, 2020, 2021, 2022, 2023, 2024])

In [15]:
df = df_gdp.merge(df_income, on=["State", "Year"], how="outer")
df = df.merge(df_real_income, on=["State", "Year"], how="outer")
df = df.merge(df_rpp, on=["State", "Year"], how="outer")

In [16]:
df.head()

     State  Year       GDP  Income_pc  Real_Income_pc  RPP
0  Alabama  1997  105381.4    21487.0             NaN  NaN
1  Alabama  1998  110838.8    22651.0             NaN  NaN
2  Alabama  1999  116514.3    23296.0             NaN  NaN
3  Alabama  2000  120522.6    24258.0             NaN  NaN
4  Alabama  2001  123534.5    25046.0             NaN  NaN

In [26]:
for i in range(1997,2008):
    df = df[df["Year"]!= i]

In [27]:
df.head()

      State  Year       GDP  Income_pc  Real_Income_pc     RPP
11  Alabama  2008  174665.6    33441.0         42219.0  88.901
12  Alabama  2009  170876.5    32717.0         41966.0  87.786
13  Alabama  2010  177510.7    33848.0         41709.0  89.783
14  Alabama  2011  182896.7    34884.0         41819.0  90.011
15  Alabama  2012  188280.7    35559.0         41592.0  90.559

In [28]:
df.tail()

        State  Year      GDP  Income_pc  Real_Income_pc     RPP
1423  Wyoming  2020  36982.7    65093.0         67906.0  91.836
1424  Wyoming  2021  42410.6    71459.0         71860.0  91.440
1425  Wyoming  2022  49570.4    77768.0         73081.0  91.767
1426  Wyoming  2023  51350.1    83038.0         75323.0  91.551
1427  Wyoming  2024  51498.1    86477.0         75501.0  92.691

In [29]:
df.head(50)

      State  Year       GDP  Income_pc  Real_Income_pc      RPP
11  Alabama  2008  174665.6    33441.0         42219.0   88.901
12  Alabama  2009  170876.5    32717.0         41966.0   87.786
13  Alabama  2010  177510.7    33848.0         41709.0   89.783
14  Alabama  2011  182896.7    34884.0         41819.0   90.011
15  Alabama  2012  188280.7    35559.0         41592.0   90.559
16  Alabama  2013  193981.5    35706.0         41325.0   90.324
17  Alabama  2014  197064.4    36722.0         41984.0   90.175
18  Alabama  2015  203113.3    38189.0         43809.0   89.741
19  Alabama  2016  208824.3    38704.0         43554.0   90.609
20  Alabama  2017  216615.5    39968.0         44481.0   90.065
21  Alabama  2018  226263.8    41324.0         46440.0   87.378
22  Alabama  2019  234798.2    42998.0         47130.0   88.303
23  Alabama  2020  235859.0    45872.0         50186.0   87.569
24  Alabama  2021  260325.0    50638.0         52875.0   88.062
25  Alabama  2022  286873.3    51697.0         50649.0   88.021
26  Alabama  2023  309543.8    54612.0         50902.0   89.097
27  Alabama  2024  325345.1    57311.0         52216.0   88.823
39   Alaska  2008   55246.7    47800.0         51647.0  103.878
40   Alaska  2009   50165.9    47211.0         50081.0  106.147
41   Alaska  2010   53654.0    49543.0         53163.0  103.099
42   Alaska  2011   56912.3    52415.0         54766.0  103.274
43   Alaska  2012   58320.7    53340.0         55096.0  102.548
44   Alaska  2013   57533.0    52252.0         53525.0  102.052
45   Alaska  2014   56587.4    55098.0         55480.0  102.386
46   Alaska  2015   51574.2    56714.0         56528.0  103.287
47   Alaska  2016   51121.8    55536.0         54411.0  104.073
48   Alaska  2017   53550.9    56500.0         54022.0  104.833
49   Alaska  2018   54762.0    58997.0         55403.0  104.565
50   Alaska  2019   54549.6    60504.0         56834.0  103.041
51   Alaska  2020   51861.7    61903.0         58522.0  101.339
52   Alaska  2021   59363.0    65803.0         57677.0  104.907
53   Alaska  2022   65682.5    69160.0         58413.0  102.101
54   Alaska  2023   68232.7    72398.0         58204.0  103.297
55   Alaska  2024   71567.2    76234.0         60272.0  102.359
67  Arizona  2008  261005.8    35586.0         38966.0  102.504
68  Arizona  2009  244862.2    33467.0         36634.0  102.865
69  Arizona  2010  250527.0    33778.0         37162.0  100.558
70  Arizona  2011  261691.4    35263.0         38403.0   99.083
71  Arizona  2012  272703.3    36364.0         39284.0   98.050
72  Arizona  2013  278679.5    36918.0         39204.0   98.441
73  Arizona  2014  286676.0    38268.0         40281.0   97.944
74  Arizona  2015  298942.2    39888.0         41960.0   97.865
75  Arizona  2016  313787.1    41173.0         42568.0   98.622
76  Arizona  2017  333099.0    43255.0         44279.0   97.915
77  Arizona  2018  353671.0    45297.0         45675.0   97.381
78  Arizona  2019  375376.7    47718.0         47236.0   97.779
79  Arizona  2020  390503.2    52077.0         50292.0   99.203
80  Arizona  2021  438136.0    57175.0         54424.0   96.600
81  Arizona  2022  488722.2    59060.0         50935.0   99.992
82  Arizona  2023  530105.0    63032.0         51960.0  100.742

In [30]:
df = df.reset_index(drop=True)

In [31]:
df.head()

     State  Year       GDP  Income_pc  Real_Income_pc     RPP
0  Alabama  2008  174665.6    33441.0         42219.0  88.901
1  Alabama  2009  170876.5    32717.0         41966.0  87.786
2  Alabama  2010  177510.7    33848.0         41709.0  89.783
3  Alabama  2011  182896.7    34884.0         41819.0  90.011
4  Alabama  2012  188280.7    35559.0         41592.0  90.559

In [32]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 867 entries, 0 to 866
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   State           867 non-null    str
 1   Year            867 non-null    int64
 2   GDP             867 non-null    float64
 3   Income_pc       867 non-null    float64
 4   Real_Income_pc  867 non-null    float64
 5   RPP             867 non-null    float64
dtypes: float64(4), int64(1), str(1)
memory usage: 40.8 KB

In [33]:
df["State"].nunique(), df["Year"].nunique()

(51, 17)

In [34]:
df.shape

(867, 6)

In [35]:
df.groupby("State")["Year"].count()

State
Alabama                 17
Alaska                  17
Arizona                 17
Arkansas                17
California              17
Colorado                17
Connecticut             17
Delaware                17
District of Columbia    17
Florida                 17
Georgia                 17
Hawaii                  17
Idaho                   17
Illinois                17
Indiana                 17
Iowa                    17
Kansas                  17
Kentucky                17
Louisiana               17
Maine                   17
Maryland                17
Massachusetts           17
Michigan                17
Minnesota               17
Mississippi             17
Missouri                17
Montana                 17
Nebraska                17
Nevada                  17
New Hampshire           17
New Jersey              17
New Mexico              17
New York                17
North Carolina          17
North Dakota            17
Ohio                    17
Oklahoma                17
Oregon                  17
Pennsylvania            17
Rhode Island            17
South Carolina          17
South Dakota            17
Tennessee               17
Texas                   17
Utah                    17
Vermont                 17
Virginia                17
Washington              17
West Virginia           17
Wisconsin               17
Wyoming                 17
Name: Year, dtype: int64

In [36]:
df.duplicated(subset=["State", "Year"]).sum()

np.int64(0)

In [39]:
pd.options.display.float_format = '{:,.0f}'.format

In [40]:
df.describe()

       Year       GDP  Income_pc  Real_Income_pc  RPP
count   867       867        867             867  867
mean  2,016   387,286     51,314          51,366   98
std       5   506,742     13,075           7,771    7
min   2,008    26,140     30,220          35,790   85
25%   2,012    94,266     41,158          45,706   92
50%   2,016   234,022     48,578          50,686   97
75%   2,020   466,581     59,220          56,142  102
max   2,024 4,048,108    111,185          81,872  114

In [41]:
df.columns = df.columns.str.lower()

In [43]:
print(df.columns)

Index(['state', 'year', 'gdp', 'income_pc', 'real_income_pc', 'rpp'], dtype='str')

In [44]:
df.head()

     state  year     gdp  income_pc  real_income_pc  rpp
0  Alabama  2008 174,666     33,441          42,219   89
1  Alabama  2009 170,876     32,717          41,966   88
2  Alabama  2010 177,511     33,848          41,709   90
3  Alabama  2011 182,897     34,884          41,819   90
4  Alabama  2012 188,281     35,559          41,592   91

In [46]:
pd.options.display.float_format = '{:,.2f}'.format

In [49]:
df.describe()

          year          gdp  income_pc  real_income_pc    rpp
count   867.00       867.00     867.00          867.00 867.00
mean  2,016.00   387,285.55  51,314.05       51,366.15  97.50
std       4.90   506,742.05  13,075.49        7,770.85   6.94
min   2,008.00    26,140.40  30,220.00       35,790.00  85.02
25%   2,012.00    94,266.05  41,158.50       45,706.50  91.84
50%   2,016.00   234,022.20  48,578.00       50,686.00  96.72
75%   2,020.00   466,580.60  59,219.50       56,142.00 102.41
max   2,024.00 4,048,108.10 111,185.00       81,872.00 114.24

In [50]:
df.to_csv("../data/processed/master_dataset_v1.csv", index=False)